  cod-account 
  cod-activate_breakpoints 
  cod-add 
  cod-archive 
  cod-arrow_both 
  cod-arrow_down 
  cod-arrow_left 
  cod-arrow_right 
  cod-arrow_small_down 
  cod-arrow_small_left 
  cod-arrow_small_right 
  cod-arrow_small_up 
  cod-arrow_swap 
  cod-arrow_up 
  cod-azure 
  cod-azure_devops 
  cod-beaker 
  cod-beaker_stop 
  cod-bell 
  cod-bell_dot 
  cod-bold 
  cod-book 
  cod-bookmark 
  cod-bracket_dot 
  cod-bracket_error 
  cod-briefcase 
  cod-broadcast 
  cod-browser 
  cod-bug 
  cod-calendar 
  cod-call_incoming 
  cod-call_outgoing 
  cod-case_sensitive 
  cod-check 
  cod-check_all 
  cod-checklist 
  cod-chevron_down 
  cod-chevron_left 
  cod-chevron_right 
  cod-chevron_up 
  cod-chrome_close 
  cod-chrome_maximize 
  cod-chrome_minimize 
  cod-chrome_restore 
  cod-circle 
  cod-circle_filled 
  cod-circle_large 
  cod-circle_large_filled 
  cod-circle_slash 
  cod-circle_small_filled 
  cod-circuit_board 
  cod-clear_all 
  cod-clippy 
  cod-close 
  cod-close_all 
  cod-cloud 
  cod-cloud_download 
  cod-cloud_upload 
  cod-code 
  cod-collapse_all 
  cod-color_mode 
  cod-combine 
  cod-comment 
  cod-comment_discussion 
  cod-compass 
  cod-compass_active 
  cod-compass_dot 
  cod-copy 
  cod-credit_card 
  cod-dash 
  cod-dashboard 
  cod-database 
  cod-debug 
  cod-debug_all 
  cod-debug_alt 
  cod-debug_alt_small 
  cod-debug_breakpoint_conditional 
  cod-debug_breakpoint_conditional_unverified 
  cod-debug_breakpoint_data 
  cod-debug_breakpoint_data_unverified 
  cod-debug_breakpoint_function 
  cod-debug_breakpoint_function_unverified 
  cod-debug_breakpoint_log 
  cod-debug_breakpoint_log_unverified 
  cod-debug_breakpoint_unsupported 
  cod-debug_console 
  cod-debug_continue 
  cod-debug_continue_small 
  cod-debug_coverage 
  cod-debug_disconnect 
  cod-debug_line_by_line 
  cod-debug_pause 
  cod-debug_rerun 
  cod-debug_restart 
  cod-debug_restart_frame 
  cod-debug_reverse_continue 
  cod-debug_stackframe 
  cod-debug_stackframe_active 
  cod-debug_start 
  cod-debug_step_back 
  cod-debug_step_into 
  cod-debug_step_out 
  cod-debug_step_over 
  cod-debug_stop 
  cod-desktop_download 
  cod-device_camera 
  cod-device_camera_video 
  cod-device_mobile 
  cod-diff 
  cod-diff_added 
  cod-diff_ignored 
  cod-diff_modified 
  cod-diff_removed 
  cod-diff_renamed 
  cod-discard 
  cod-edit 
  cod-editor_layout 
  cod-ellipsis 
  cod-empty_window 
  cod-error 
  cod-exclude 
  cod-expand_all 
  cod-export 
  cod-extensions 
  cod-eye 
  cod-eye_closed 
  cod-feedback 
  cod-file 
  cod-file_binary 
  cod-file_code 
  cod-file_media 
  cod-file_pdf 
  cod-file_submodule 
  cod-file_symlink_directory 
  cod-file_symlink_file 
  cod-file_zip 
  cod-files 
  cod-filter 
  cod-filter_filled 
  cod-flame 
  cod-fold 
  cod-fold_down 
  cod-fold_up 
  cod-folder 
  cod-folder_active 
  cod-folder_library 
  cod-folder_opened 
  cod-gear 
  cod-gift 
  cod-gist_secret 
  cod-git_commit 
  cod-git_compare 
  cod-git_merge 
  cod-git_pull_request 
  cod-git_pull_request_closed 
  cod-git_pull_request_create 
  cod-git_pull_request_draft 
  cod-github 
  cod-github_action 
  cod-github_alt 
  cod-github_inverted 
  cod-globe 
  cod-go_to_file 
  cod-grabber 
  cod-graph 
  cod-graph_left 
  cod-graph_line 
  cod-graph_scatter 
  cod-gripper 
  cod-group_by_ref_type 
  cod-heart 
  cod-history 
  cod-home 
  cod-horizontal_rule 
  cod-hubot 
  cod-inbox 
  cod-info 
  cod-inspect 
  cod-issue_draft 
  cod-issue_reopened 
  cod-issues 
  cod-italic 
  cod-jersey 
  cod-json 
  cod-kebab_vertical 
  cod-key 
  cod-law 
  cod-layers 
  cod-layers_active 
  cod-layers_dot 
  cod-layout 
  cod-library 
  cod-lightbulb 
  cod-lightbulb_autofix 
  cod-link 
  cod-link_external 
  cod-list_filter 
  cod-list_flat 
  cod-list_ordered 
  cod-list_selection 
  cod-list_tree 
  cod-list_unordered 
  cod-live_share 
  cod-loading 
  cod-location 
  cod-lock 
  cod-lock_small 
  cod-magnet 
  cod-mail 
  cod-mail_read 
  cod-markdown 
  cod-megaphone 
  cod-mention 
  cod-menu 
  cod-merge 
  cod-milestone 
  cod-mirror 
  cod-mortar_board 
  cod-move 
  cod-multiple_windows 
  cod-mute 
  cod-new_file 
  cod-new_folder 
  cod-newline 
  cod-no_newline 
  cod-note 
  cod-notebook 
  cod-notebook_template 
  cod-octoface 
  cod-open_preview 
  cod-organization 
  cod-output 
  cod-package 
  cod-paintcan 
  cod-pass 
  cod-pass_filled 
  cod-person 
  cod-person_add 
  cod-pie_chart 
  cod-pin 
  cod-pinned 
  cod-pinned_dirty 
  cod-play 
  cod-play_circle 
  cod-plug 
  cod-preserve_case 
  cod-preview 
  cod-primitive_square 
  cod-project 
  cod-pulse 
  cod-question 
  cod-quote 
  cod-radio_tower 
  cod-reactions 
  cod-record 
  cod-record_keys 
  cod-redo 
  cod-references 
  cod-refresh 
  cod-regex 
  cod-remote 
  cod-remote_explorer 
  cod-remove 
  cod-replace 
  cod-replace_all 
  cod-reply 
  cod-repo 
  cod-repo_clone 
  cod-repo_force_push 
  cod-repo_forked 
  cod-repo_pull 
  cod-repo_push 
  cod-report 
  cod-request_changes 
  cod-rocket 
  cod-root_folder 
  cod-root_folder_opened 
  cod-rss 
  cod-ruby 
  cod-run_above 
  cod-run_all 
  cod-run_below 
  cod-run_errors 
  cod-save 
  cod-save_all 
  cod-save_as 
  cod-screen_full 
  cod-screen_normal 
  cod-search 
  cod-search_stop 
  cod-server 
  cod-server_environment 
  cod-server_process 
  cod-settings 
  cod-settings_gear 
  cod-shield 
  cod-sign_in 
  cod-sign_out 
  cod-smiley 
  cod-sort_precedence 
  cod-source_control 
  cod-split_horizontal 
  cod-split_vertical 
  cod-squirrel 
  cod-star_empty 
  cod-star_full 
  cod-star_half 
  cod-stop_circle 
  cod-symbol_array 
  cod-symbol_boolean 
  cod-symbol_class 
  cod-symbol_color 
  cod-symbol_constant 
  cod-symbol_enum 
  cod-symbol_enum_member 
  cod-symbol_event 
  cod-symbol_field 
  cod-symbol_file 
  cod-symbol_interface 
  cod-symbol_key 
  cod-symbol_keyword 
  cod-symbol_method 
  cod-symbol_misc 
  cod-symbol_namespace 
  cod-symbol_numeric 
  cod-symbol_operator 
  cod-symbol_parameter 
  cod-symbol_property 
  cod-symbol_ruler 
  cod-symbol_snippet 
  cod-symbol_string 
  cod-symbol_structure 
  cod-symbol_variable 
  cod-sync 
  cod-sync_ignored 
  cod-table 
  cod-tag 
  cod-tasklist 
  cod-telescope 
  cod-terminal 
  cod-terminal_bash 
  cod-terminal_cmd 
  cod-terminal_debian 
  cod-terminal_linux 
  cod-terminal_powershell 
  cod-terminal_tmux 
  cod-terminal_ubuntu 
  cod-text_size 
  cod-three_bars 
  cod-thumbsdown 
  cod-thumbsup 
  cod-tools 
  cod-trash 
  cod-triangle_down 
  cod-triangle_left 
  cod-triangle_right 
  cod-triangle_up 
  cod-twitter 
  cod-type_hierarchy 
  cod-type_hierarchy_sub 
  cod-type_hierarchy_super 
  cod-unfold 
  cod-ungroup_by_ref_type 
  cod-unlock 
  cod-unmute 
  cod-unverified 
  cod-variable_group 
  cod-verified 
  cod-verified_filled 
  cod-versions 
  cod-vm 
  cod-vm_active 
  cod-vm_connect 
  cod-vm_outline 
  cod-vm_running 
  cod-wand 
  cod-warning 
  cod-watch 
  cod-whitespace 
  cod-whole_word 
  cod-window 
  cod-word_wrap 
  cod-workspace_trusted 
  cod-workspace_unknown 
  cod-workspace_untrusted 
  cod-zoom_in 
  cod-zoom_out 
  custom-c 
  custom-cpp 
  custom-crystal 
  custom-default 
  custom-electron 
  custom-elixir 
  custom-elm 
  custom-emacs 
  custom-folder 
  custom-folder_config 
  custom-folder_git 
  custom-folder_git_branch 
  custom-folder_github 
  custom-folder_npm 
  custom-folder_open 
  custom-go 
  custom-home 
  custom-kotlin 
  custom-msdos 
  custom-orgmode 
  custom-play_arrow 
  custom-puppet 
  custom-purescript 
  custom-vim 
  custom-windows 
  dev-android 
  dev-angular 
  dev-appcelerator 
  dev-apple 
  dev-appstore 
  dev-aptana 
  dev-asterisk 
  dev-atlassian 
  dev-atom 
  dev-aws 
  dev-backbone 
  dev-bing_small 
  dev-bintray 
  dev-bitbucket 
  dev-blackberry 
  dev-bootstrap 
  dev-bower 
  dev-brackets 
  dev-bugsense 
  dev-celluloid 
  dev-chart 
  dev-chrome 
  dev-cisco 
  dev-clojure 
  dev-clojure_alt 
  dev-cloud9 
  dev-coda 
  dev-code 
  dev-code_badge 
  dev-codeigniter 
  dev-codepen 
  dev-codrops 
  dev-coffeescript 
  dev-compass 
  dev-composer 
  dev-creativecommons 
  dev-creativecommons_badge 
  dev-css3 
  dev-css3_full 
  dev-css_tricks 
  dev-cssdeck 
  dev-dart 
  dev-database 
  dev-debian 
  dev-digital_ocean 
  dev-django 
  dev-dlang 
  dev-docker 
  dev-doctrine 
  dev-dojo 
  dev-dotnet 
  dev-dreamweaver 
  dev-dropbox 
  dev-drupal 
  dev-eclipse 
  dev-ember 
  dev-envato 
  dev-erlang 
  dev-extjs 
  dev-firebase 
  dev-firefox 
  dev-fsharp 
  dev-ghost 
  dev-ghost_small 
  dev-git 
  dev-git_branch 
  dev-git_commit 
  dev-git_compare 
  dev-git_merge 
  dev-git_pull_request 
  dev-github 
  dev-github_alt 
  dev-github_badge 
  dev-github_full 
  dev-gnu 
  dev-go 
  dev-google_cloud_platform 
  dev-google_drive 
  dev-grails 
  dev-groovy 
  dev-grunt 
  dev-gulp 
  dev-hackernews 
  dev-haskell 
  dev-heroku 
  dev-html5 
  dev-html5_3d_effects 
  dev-html5_connectivity 
  dev-html5_device_access 
  dev-html5_multimedia 
  dev-ie 
  dev-illustrator 
  dev-intellij 
  dev-ionic 
  dev-java 
  dev-javascript 
  dev-javascript_badge 
  dev-javascript_shield 
  dev-jekyll_small 
  dev-jenkins 
  dev-jira 
  dev-joomla 
  dev-jquery 
  dev-jquery_ui 
  dev-komodo 
  dev-krakenjs 
  dev-krakenjs_badge 
  dev-laravel 
  dev-less 
  dev-linux 
  dev-magento 
  dev-mailchimp 
  dev-markdown 
  dev-materializecss 
  dev-meteor 
  dev-meteorfull 
  dev-mitlicence 
  dev-modernizr 
  dev-mongodb 
  dev-mootools 
  dev-mootools_badge 
  dev-mozilla 
  dev-msql_server 
  dev-mysql 
  dev-nancy 
  dev-netbeans 
  dev-netmagazine 
  dev-nginx 
  dev-nodejs 
  dev-nodejs_small 
  dev-npm 
  dev-onedrive 
  dev-openshift 
  dev-opensource 
  dev-opera 
  dev-perl 
  dev-phonegap 
  dev-photoshop 
  dev-php 
  dev-postgresql 
  dev-prolog 
  dev-python 
  dev-rackspace 
  dev-raphael 
  dev-rasberry_pi 
  dev-react 
  dev-redhat 
  dev-redis 
  dev-requirejs 
  dev-responsive 
  dev-ruby 
  dev-ruby_on_rails 
  dev-ruby_rough 
  dev-rust 
  dev-safari 
  dev-sass 
  dev-scala 
  dev-scriptcs 
  dev-scrum 
  dev-senchatouch 
  dev-sizzlejs 
  dev-smashing_magazine 
  dev-snap_svg 
  dev-sqllite 
  dev-stackoverflow 
  dev-streamline 
  dev-stylus 
  dev-sublime 
  dev-swift 
  dev-symfony 
  dev-symfony_badge 
  dev-techcrunch 
  dev-terminal 
  dev-terminal_badge 
  dev-travis 
  dev-trello 
  dev-typo3 
  dev-ubuntu 
  dev-uikit 
  dev-unity_small 
  dev-vim 
  dev-visualstudio 
  dev-w3c 
  dev-webplatform 
  dev-windows 
  dev-wordpress 
  dev-yahoo 
  dev-yahoo_small 
  dev-yeoman 
  dev-yii 
  dev-zend 
  fa-500px 
  fa-address_book 
  fa-address_book_o 
  fa-address_card 
  fa-address_card_o 
  fa-adjust 
  fa-adn 
  fa-align_center 
  fa-align_justify 
  fa-align_left 
  fa-align_right 
  fa-amazon 
  fa-ambulance 
  fa-american_sign_language_interpreting 
  fa-anchor 
  fa-android 
  fa-angellist 
  fa-angle_double_down 
  fa-angle_double_left 
  fa-angle_double_right 
  fa-angle_double_up 
  fa-angle_down 
  fa-angle_left 
  fa-angle_right 
  fa-angle_up 
  fa-apple 
  fa-archive 
  fa-area_chart 
  fa-arrow_circle_down 
  fa-arrow_circle_left 
  fa-arrow_circle_o_down 
  fa-arrow_circle_o_left 
  fa-arrow_circle_o_right 
  fa-arrow_circle_o_up 
  fa-arrow_circle_right 
  fa-arrow_circle_up 
  fa-arrow_down 
  fa-arrow_left 
  fa-arrow_right 
  fa-arrow_up 
  fa-arrows 
  fa-arrows_alt 
  fa-arrows_h 
  fa-arrows_v 
  fa-asl_interpreting 
  fa-assistive_listening_systems 
  fa-asterisk 
  fa-at 
  fa-audio_description 
  fa-automobile 
  fa-backward 
  fa-balance_scale 
  fa-ban 
  fa-bandcamp 
  fa-bank 
  fa-bar_chart 
  fa-bar_chart_o 
  fa-barcode 
  fa-bars 
  fa-bath 
  fa-bathtub 
  fa-battery 
  fa-battery_0 
  fa-battery_1 
  fa-battery_2 
  fa-battery_3 
  fa-battery_4 
  fa-battery_empty 
  fa-battery_full 
  fa-battery_half 
  fa-battery_quarter 
  fa-battery_three_quarters 
  fa-bed 
  fa-beer 
  fa-behance 
  fa-behance_square 
  fa-bell 
  fa-bell_o 
  fa-bell_slash 
  fa-bell_slash_o 
  fa-bicycle 
  fa-binoculars 
  fa-birthday_cake 
  fa-bitbucket 
  fa-bitbucket_square 
  fa-bitcoin 
  fa-black_tie 
  fa-blind 
  fa-bluetooth 
  fa-bluetooth_b 
  fa-bold 
  fa-bolt 
  fa-bomb 
  fa-book 
  fa-bookmark 
  fa-bookmark_o 
  fa-braille 
  fa-briefcase 
  fa-btc 
  fa-bug 
  fa-building 
  fa-building_o 
  fa-bullhorn 
  fa-bullseye 
  fa-bus 
  fa-buysellads 
  fa-cab 
  fa-calculator 
  fa-calendar 
  fa-calendar_check_o 
  fa-calendar_minus_o 
  fa-calendar_o 
  fa-calendar_plus_o 
  fa-calendar_times_o 
  fa-camera 
  fa-camera_retro 
  fa-car 
  fa-caret_down 
  fa-caret_left 
  fa-caret_right 
  fa-caret_square_o_down 
  fa-caret_square_o_left 
  fa-caret_square_o_right 
  fa-caret_square_o_up 
  fa-caret_up 
  fa-cart_arrow_down 
  fa-cart_plus 
  fa-cc 
  fa-cc_amex 
  fa-cc_diners_club 
  fa-cc_discover 
  fa-cc_jcb 
  fa-cc_mastercard 
  fa-cc_paypal 
  fa-cc_stripe 
  fa-cc_visa 
  fa-certificate 
  fa-chain 
  fa-chain_broken 
  fa-check 
  fa-check_circle 
  fa-check_circle_o 
  fa-check_square 
  fa-check_square_o 
  fa-chevron_circle_down 
  fa-chevron_circle_left 
  fa-chevron_circle_right 
  fa-chevron_circle_up 
  fa-chevron_down 
  fa-chevron_left 
  fa-chevron_right 
  fa-chevron_up 
  fa-child 
  fa-chrome 
  fa-circle 
  fa-circle_o 
  fa-circle_o_notch 
  fa-circle_thin 
  fa-clipboard 
  fa-clock_o 
  fa-clone 
  fa-close 
  fa-cloud 
  fa-cloud_download 
  fa-cloud_upload 
  fa-cny 
  fa-code 
  fa-code_fork 
  fa-codepen 
  fa-codiepie 
  fa-coffee 
  fa-cog 
  fa-cogs 
  fa-columns 
  fa-comment 
  fa-comment_o 
  fa-commenting 
  fa-commenting_o 
  fa-comments 
  fa-comments_o 
  fa-compass 
  fa-compress 
  fa-connectdevelop 
  fa-contao 
  fa-copy 
  fa-copyright 
  fa-creative_commons 
  fa-credit_card 
  fa-credit_card_alt 
  fa-crop 
  fa-crosshairs 
  fa-css3 
  fa-cube 
  fa-cubes 
  fa-cut 
  fa-cutlery 
  fa-dashboard 
  fa-dashcube 
  fa-database 
  fa-deaf 
  fa-deafness 
  fa-dedent 
  fa-delicious 
  fa-desktop 
  fa-deviantart 
  fa-diamond 
  fa-digg 
  fa-dollar 
  fa-dot_circle_o 
  fa-download 
  fa-dribbble 
  fa-drivers_license 
  fa-drivers_license_o 
  fa-dropbox 
  fa-drupal 
  fa-edge 
  fa-edit 
  fa-eercast 
  fa-eject 
  fa-ellipsis_h 
  fa-ellipsis_v 
  fa-empire 
  fa-envelope 
  fa-envelope_o 
  fa-envelope_open 
  fa-envelope_open_o 
  fa-envelope_square 
  fa-envira 
  fa-eraser 
  fa-etsy 
  fa-eur 
  fa-euro 
  fa-exchange 
  fa-exclamation 
  fa-exclamation_circle 
  fa-exclamation_triangle 
  fa-expand 
  fa-expeditedssl 
  fa-external_link 
  fa-external_link_square 
  fa-eye 
  fa-eye_slash 
  fa-eyedropper 
  fa-fa 
  fa-facebook 
  fa-facebook_f 
  fa-facebook_official 
  fa-facebook_square 
  fa-fast_backward 
  fa-fast_forward 
  fa-fax 
  fa-feed 
  fa-female 
  fa-fighter_jet 
  fa-file 
  fa-file_archive_o 
  fa-file_audio_o 
  fa-file_code_o 
  fa-file_excel_o 
  fa-file_image_o 
  fa-file_movie_o 
  fa-file_o 
  fa-file_pdf_o 
  fa-file_photo_o 
  fa-file_picture_o 
  fa-file_powerpoint_o 
  fa-file_sound_o 
  fa-file_text 
  fa-file_text_o 
  fa-file_video_o 
  fa-file_word_o 
  fa-file_zip_o 
  fa-files_o 
  fa-film 
  fa-filter 
  fa-fire 
  fa-fire_extinguisher 
  fa-firefox 
  fa-first_order 
  fa-flag 
  fa-flag_checkered 
  fa-flag_o 
  fa-flash 
  fa-flask 
  fa-flickr 
  fa-floppy_o 
  fa-folder 
  fa-folder_o 
  fa-folder_open 
  fa-folder_open_o 
  fa-font 
  fa-font_awesome 
  fa-fonticons 
  fa-fort_awesome 
  fa-forumbee 
  fa-forward 
  fa-foursquare 
  fa-free_code_camp 
  fa-frown_o 
  fa-futbol_o 
  fa-gamepad 
  fa-gavel 
  fa-gbp 
  fa-ge 
  fa-gear 
  fa-gears 
  fa-genderless 
  fa-get_pocket 
  fa-gg 
  fa-gg_circle 
  fa-gift 
  fa-git 
  fa-git_square 
  fa-github 
  fa-github_alt 
  fa-github_square 
  fa-gitlab 
  fa-gittip 
  fa-glass 
  fa-glide 
  fa-glide_g 
  fa-globe 
  fa-google 
  fa-google_plus 
  fa-google_plus_circle 
  fa-google_plus_official 
  fa-google_plus_square 
  fa-google_wallet 
  fa-graduation_cap 
  fa-gratipay 
  fa-grav 
  fa-group 
  fa-h_square 
  fa-hacker_news 
  fa-hand_grab_o 
  fa-hand_lizard_o 
  fa-hand_o_down 
  fa-hand_o_left 
  fa-hand_o_right 
  fa-hand_o_up 
  fa-hand_paper_o 
  fa-hand_peace_o 
  fa-hand_pointer_o 
  fa-hand_rock_o 
  fa-hand_scissors_o 
  fa-hand_spock_o 
  fa-hand_stop_o 
  fa-handshake_o 
  fa-hard_of_hearing 
  fa-hashtag 
  fa-hdd_o 
  fa-header 
  fa-headphones 
  fa-heart 
  fa-heart_o 
  fa-heartbeat 
  fa-history 
  fa-home 
  fa-hospital_o 
  fa-hotel 
  fa-hourglass 
  fa-hourglass_1 
  fa-hourglass_2 
  fa-hourglass_3 
  fa-hourglass_end 
  fa-hourglass_half 
  fa-hourglass_o 
  fa-hourglass_start 
  fa-houzz 
  fa-html5 
  fa-i_cursor 
  fa-id_badge 
  fa-id_card 
  fa-id_card_o 
  fa-ils 
  fa-image 
  fa-imdb 
  fa-inbox 
  fa-indent 
  fa-industry 
  fa-info 
  fa-info_circle 
  fa-inr 
  fa-instagram 
  fa-institution 
  fa-internet_explorer 
  fa-intersex 
  fa-ioxhost 
  fa-italic 
  fa-joomla 
  fa-jpy 
  fa-jsfiddle 
  fa-key 
  fa-keyboard_o 
  fa-krw 
  fa-language 
  fa-laptop 
  fa-lastfm 
  fa-lastfm_square 
  fa-leaf 
  fa-leanpub 
  fa-legal 
  fa-lemon_o 
  fa-level_down 
  fa-level_up 
  fa-life_bouy 
  fa-life_buoy 
  fa-life_ring 
  fa-life_saver 
  fa-lightbulb_o 
  fa-line_chart 
  fa-link 
  fa-linkedin 
  fa-linkedin_square 
  fa-linode 
  fa-linux 
  fa-list 
  fa-list_alt 
  fa-list_ol 
  fa-list_ul 
  fa-location_arrow 
  fa-lock 
  fa-long_arrow_down 
  fa-long_arrow_left 
  fa-long_arrow_right 
  fa-long_arrow_up 
  fa-low_vision 
  fa-magic 
  fa-magnet 
  fa-mail_forward 
  fa-mail_reply 
  fa-mail_reply_all 
  fa-male 
  fa-map 
  fa-map_marker 
  fa-map_o 
  fa-map_pin 
  fa-map_signs 
  fa-mars 
  fa-mars_double 
  fa-mars_stroke 
  fa-mars_stroke_h 
  fa-mars_stroke_v 
  fa-maxcdn 
  fa-meanpath 
  fa-medium 
  fa-medkit 
  fa-meetup 
  fa-meh_o 
  fa-mercury 
  fa-microchip 
  fa-microphone 
  fa-microphone_slash 
  fa-minus 
  fa-minus_circle 
  fa-minus_square 
  fa-minus_square_o 
  fa-mixcloud 
  fa-mobile 
  fa-mobile_phone 
  fa-modx 
  fa-money 
  fa-moon_o 
  fa-mortar_board 
  fa-motorcycle 
  fa-mouse_pointer 
  fa-music 
  fa-navicon 
  fa-neuter 
  fa-newspaper_o 
  fa-object_group 
  fa-object_ungroup 
  fa-odnoklassniki 
  fa-odnoklassniki_square 
  fa-opencart 
  fa-openid 
  fa-opera 
  fa-optin_monster 
  fa-outdent 
  fa-pagelines 
  fa-paint_brush 
  fa-paper_plane 
  fa-paper_plane_o 
  fa-paperclip 
  fa-paragraph 
  fa-paste 
  fa-pause 
  fa-pause_circle 
  fa-pause_circle_o 
  fa-paw 
  fa-paypal 
  fa-pencil 
  fa-pencil_square 
  fa-pencil_square_o 
  fa-percent 
  fa-phone 
  fa-phone_square 
  fa-photo 
  fa-picture_o 
  fa-pie_chart 
  fa-pied_piper 
  fa-pied_piper_alt 
  fa-pied_piper_pp 
  fa-pinterest 
  fa-pinterest_p 
  fa-pinterest_square 
  fa-plane 
  fa-play 
  fa-play_circle 
  fa-play_circle_o 
  fa-plug 
  fa-plus 
  fa-plus_circle 
  fa-plus_square 
  fa-plus_square_o 
  fa-podcast 
  fa-power_off 
  fa-print 
  fa-product_hunt 
  fa-puzzle_piece 
  fa-qq 
  fa-qrcode 
  fa-question 
  fa-question_circle 
  fa-question_circle_o 
  fa-quora 
  fa-quote_left 
  fa-quote_right 
  fa-ra 
  fa-random 
  fa-ravelry 
  fa-rebel 
  fa-recycle 
  fa-reddit 
  fa-reddit_alien 
  fa-reddit_square 
  fa-refresh 
  fa-registered 
  fa-remove 
  fa-renren 
  fa-reorder 
  fa-repeat 
  fa-reply 
  fa-reply_all 
  fa-resistance 
  fa-retweet 
  fa-rmb 
  fa-road 
  fa-rocket 
  fa-rotate_left 
  fa-rotate_right 
  fa-rouble 
  fa-rss 
  fa-rss_square 
  fa-rub 
  fa-ruble 
  fa-rupee 
  fa-s15 
  fa-safari 
  fa-save 
  fa-scissors 
  fa-scribd 
  fa-search 
  fa-search_minus 
  fa-search_plus 
  fa-sellsy 
  fa-send 
  fa-send_o 
  fa-server 
  fa-share 
  fa-share_alt 
  fa-share_alt_square 
  fa-share_square 
  fa-share_square_o 
  fa-shekel 
  fa-sheqel 
  fa-shield 
  fa-ship 
  fa-shirtsinbulk 
  fa-shopping_bag 
  fa-shopping_basket 
  fa-shopping_cart 
  fa-shower 
  fa-sign_in 
  fa-sign_language 
  fa-sign_out 
  fa-signal 
  fa-signing 
  fa-simplybuilt 
  fa-sitemap 
  fa-skyatlas 
  fa-skype 
  fa-slack 
  fa-sliders 
  fa-slideshare 
  fa-smile_o 
  fa-snapchat 
  fa-snapchat_ghost 
  fa-snapchat_square 
  fa-snowflake_o 
  fa-soccer_ball_o 
  fa-sort 
  fa-sort_alpha_asc 
  fa-sort_alpha_desc 
  fa-sort_amount_asc 
  fa-sort_amount_desc 
  fa-sort_asc 
  fa-sort_desc 
  fa-sort_down 
  fa-sort_numeric_asc 
  fa-sort_numeric_desc 
  fa-sort_up 
  fa-soundcloud 
  fa-space_shuttle 
  fa-spinner 
  fa-spoon 
  fa-spotify 
  fa-square 
  fa-square_o 
  fa-stack_exchange 
  fa-stack_overflow 
  fa-star 
  fa-star_half 
  fa-star_half_empty 
  fa-star_half_full 
  fa-star_half_o 
  fa-star_o 
  fa-steam 
  fa-steam_square 
  fa-step_backward 
  fa-step_forward 
  fa-stethoscope 
  fa-sticky_note 
  fa-sticky_note_o 
  fa-stop 
  fa-stop_circle 
  fa-stop_circle_o 
  fa-street_view 
  fa-strikethrough 
  fa-stumbleupon 
  fa-stumbleupon_circle 
  fa-subscript 
  fa-subway 
  fa-suitcase 
  fa-sun_o 
  fa-superpowers 
  fa-superscript 
  fa-support 
  fa-table 
  fa-tablet 
  fa-tachometer 
  fa-tag 
  fa-tags 
  fa-tasks 
  fa-taxi 
  fa-telegram 
  fa-television 
  fa-tencent_weibo 
  fa-terminal 
  fa-text_height 
  fa-text_width 
  fa-th 
  fa-th_large 
  fa-th_list 
  fa-themeisle 
  fa-thermometer 
  fa-thermometer_0 
  fa-thermometer_1 
  fa-thermometer_2 
  fa-thermometer_3 
  fa-thermometer_4 
  fa-thermometer_empty 
  fa-thermometer_full 
  fa-thermometer_half 
  fa-thermometer_quarter 
  fa-thermometer_three_quarters 
  fa-thumb_tack 
  fa-thumbs_down 
  fa-thumbs_o_down 
  fa-thumbs_o_up 
  fa-thumbs_up 
  fa-ticket 
  fa-times 
  fa-times_circle 
  fa-times_circle_o 
  fa-times_rectangle 
  fa-times_rectangle_o 
  fa-tint 
  fa-toggle_down 
  fa-toggle_left 
  fa-toggle_off 
  fa-toggle_on 
  fa-toggle_right 
  fa-toggle_up 
  fa-trademark 
  fa-train 
  fa-transgender 
  fa-transgender_alt 
  fa-trash 
  fa-trash_o 
  fa-tree 
  fa-trello 
  fa-tripadvisor 
  fa-trophy 
  fa-truck 
  fa-try 
  fa-tty 
  fa-tumblr 
  fa-tumblr_square 
  fa-turkish_lira 
  fa-tv 
  fa-twitch 
  fa-twitter 
  fa-twitter_square 
  fa-umbrella 
  fa-underline 
  fa-undo 
  fa-universal_access 
  fa-university 
  fa-unlink 
  fa-unlock 
  fa-unlock_alt 
  fa-unsorted 
  fa-upload 
  fa-usb 
  fa-usd 
  fa-user 
  fa-user_circle 
  fa-user_circle_o 
  fa-user_md 
  fa-user_o 
  fa-user_plus 
  fa-user_secret 
  fa-user_times 
  fa-users 
  fa-vcard 
  fa-vcard_o 
  fa-venus 
  fa-venus_double 
  fa-venus_mars 
  fa-viacoin 
  fa-viadeo 
  fa-viadeo_square 
  fa-video_camera 
  fa-vimeo 
  fa-vimeo_square 
  fa-vine 
  fa-vk 
  fa-volume_control_phone 
  fa-volume_down 
  fa-volume_off 
  fa-volume_up 
  fa-warning 
  fa-wechat 
  fa-weibo 
  fa-weixin 
  fa-whatsapp 
  fa-wheelchair 
  fa-wheelchair_alt 
  fa-wifi 
  fa-wikipedia_w 
  fa-window_close 
  fa-window_close_o 
  fa-window_maximize 
  fa-window_minimize 
  fa-window_restore 
  fa-windows 
  fa-won 
  fa-wordpress 
  fa-wpbeginner 
  fa-wpexplorer 
  fa-wpforms 
  fa-wrench 
  fa-xing 
  fa-xing_square 
  fa-y_combinator 
  fa-y_combinator_square 
  fa-yahoo 
  fa-yc 
  fa-yc_square 
  fa-yelp 
  fa-yen 
  fa-yoast 
  fa-youtube 
  fa-youtube_play 
  fa-youtube_square 
  fae-apple_fruit 
  fae-atom 
  fae-bacteria 
  fae-banana 
  fae-bath 
  fae-bed 
  fae-benzene 
  fae-bigger 
  fae-biohazard 
  fae-blogger_circle 
  fae-blogger_square 
  fae-bones 
  fae-book_open 
  fae-book_open_o 
  fae-brain 
  fae-bread 
  fae-butterfly 
  fae-carot 
  fae-cc_by 
  fae-cc_cc 
  fae-cc_nc 
  fae-cc_nc_eu 
  fae-cc_nc_jp 
  fae-cc_nd 
  fae-cc_remix 
  fae-cc_sa 
  fae-cc_share 
  fae-cc_zero 
  fae-checklist_o 
  fae-cheese 
  fae-cherry 
  fae-chess_bishop 
  fae-chess_horse 
  fae-chess_king 
  fae-chess_pawn 
  fae-chess_queen 
  fae-chess_tower 
  fae-chicken_thigh 
  fae-chilli 
  fae-chip 
  fae-cicling 
  fae-cloud 
  fae-cockroach 
  fae-coffe_beans 
  fae-coins 
  fae-comb 
  fae-comet 
  fae-crown 
  fae-cup_coffe 
  fae-dice 
  fae-disco 
  fae-dna 
  fae-donut 
  fae-dress 
  fae-drop 
  fae-ello 
  fae-envelope_open 
  fae-envelope_open_o 
  fae-equal 
  fae-equal_bigger 
  fae-feedly 
  fae-file_export 
  fae-file_import 
  fae-fingerprint 
  fae-floppy 
  fae-footprint 
  fae-freecodecamp 
  fae-galaxy 
  fae-galery 
  fae-gift_card 
  fae-glass 
  fae-google_drive 
  fae-google_play 
  fae-gps 
  fae-grav 
  fae-guitar 
  fae-gut 
  fae-halter 
  fae-hamburger 
  fae-hat 
  fae-hexagon 
  fae-high_heel 
  fae-hotdog 
  fae-ice_cream 
  fae-id_card 
  fae-imdb 
  fae-infinity 
  fae-injection 
  fae-isle 
  fae-java 
  fae-layers 
  fae-lips 
  fae-lipstick 
  fae-liver 
  fae-lollipop 
  fae-loyalty_card 
  fae-lung 
  fae-makeup_brushes 
  fae-maximize 
  fae-meat 
  fae-medicine 
  fae-microscope 
  fae-milk_bottle 
  fae-minimize 
  fae-molecule 
  fae-moon_cloud 
  fae-mountains 
  fae-mushroom 
  fae-mustache 
  fae-mysql 
  fae-nintendo 
  fae-orange 
  fae-palette_color 
  fae-peach 
  fae-pear 
  fae-pi 
  fae-pizza 
  fae-planet 
  fae-plant 
  fae-playstation 
  fae-poison 
  fae-popcorn 
  fae-popsicle 
  fae-pulse 
  fae-python 
  fae-quora_circle 
  fae-quora_square 
  fae-radioactive 
  fae-raining 
  fae-real_heart 
  fae-refrigerator 
  fae-restore 
  fae-ring 
  fae-ruby 
  fae-ruby_o 
  fae-ruler 
  fae-shirt 
  fae-slash 
  fae-smaller 
  fae-snowing 
  fae-soda 
  fae-sofa 
  fae-soup 
  fae-spermatozoon 
  fae-spin_double 
  fae-stomach 
  fae-storm 
  fae-sun_cloud 
  fae-sushi 
  fae-tacos 
  fae-telegram 
  fae-telegram_circle 
  fae-telescope 
  fae-thermometer 
  fae-thermometer_high 
  fae-thermometer_low 
  fae-thin_close 
  fae-toilet 
  fae-tools 
  fae-tooth 
  fae-tree 
  fae-triangle_ruler 
  fae-umbrella 
  fae-uterus 
  fae-virus 
  fae-w3c 
  fae-walking 
  fae-wallet 
  fae-wind 
  fae-xbox 
⏻  iec-power 
⭘  iec-power_off 
⏽  iec-power_on 
⏾  iec-sleep_mode 
⏼  iec-toggle_power 
  indent-dotted_guide 
  indent-line 
  indentation-line 
  linux-almalinux 
  linux-alpine 
  linux-aosc 
  linux-apple 
  linux-archlabs 
  linux-archlinux 
  linux-artix 
  linux-budgie 
  linux-centos 
  linux-coreos 
  linux-debian 
  linux-deepin 
  linux-devuan 
  linux-docker 
  linux-elementary 
  linux-endeavour 
  linux-fedora 
  linux-fedora_inverse 
  linux-ferris 
  linux-flathub 
  linux-freebsd 
  linux-gentoo 
  linux-gnu_guix 
  linux-illumos 
  linux-kali_linux 
  linux-linuxmint 
  linux-linuxmint_inverse 
  linux-mageia 
  linux-mandriva 
  linux-manjaro 
  linux-nixos 
  linux-openbsd 
  linux-opensuse 
  linux-parrot 
  linux-pop_os 
  linux-raspberry_pi 
  linux-redhat 
  linux-rocky_linux 
  linux-sabayon 
  linux-slackware 
  linux-slackware_inverse 
  linux-snappy 
  linux-solus 
  linux-tux 
  linux-ubuntu 
  linux-ubuntu_inverse 
  linux-void 
  linux-zorin 
  mdi-access_point 
  mdi-access_point_network 
  mdi-account 
  mdi-account_alert 
  mdi-account_box 
  mdi-account_box_outline 
𣏕  mdi-account_card_details 
  mdi-account_check 
  mdi-account_circle 
  mdi-account_convert 
﮺  mdi-account_edit 
  mdi-account_key 
  mdi-account_location 
  mdi-account_minus 
  mdi-account_multiple 
㮝  mdi-account_multiple_minus 
  mdi-account_multiple_outline 
  mdi-account_multiple_plus 
ﳾ  mdi-account_multiple_plus_outline 
  mdi-account_network 
  mdi-account_off 
  mdi-account_outline 
  mdi-account_plus 
ﳿ  mdi-account_plus_outline 
  mdi-account_remove 
  mdi-account_search 
אָ  mdi-account_settings 
אּ  mdi-account_settings_variant 
  mdi-account_star 
  mdi-account_switch 
  mdi-adjust 
  mdi-air_conditioner 
  mdi-airballoon 
  mdi-airplane 
䀘  mdi-airplane_landing 
  mdi-airplane_off 
䀹  mdi-airplane_takeoff 
  mdi-airplay 
  mdi-alarm 
ﲌ  mdi-alarm_bell 
  mdi-alarm_check 
ﲍ  mdi-alarm_light 
  mdi-alarm_multiple 
  mdi-alarm_off 
  mdi-alarm_plus 
ﮌ  mdi-alarm_snooze 
  mdi-album 
  mdi-alert 
  mdi-alert_box 
  mdi-alert_circle 
𥉉  mdi-alert_circle_outline 
﮻  mdi-alert_decagram 
  mdi-alert_octagon 
ﱥ  mdi-alert_octagram 
  mdi-alert_outline 
﮼  mdi-all_inclusive 
ﴀ  mdi-allo 
  mdi-alpha 
  mdi-alphabetical 
𥳐  mdi-altimeter 
  mdi-amazon 
  mdi-amazon_clouddrive 
  mdi-ambulance 
  mdi-amplifier 
  mdi-anchor 
  mdi-android 
  mdi-android_debug_bridge 
ﲎ  mdi-android_head 
  mdi-android_studio 
ﮰ  mdi-angular 
﮽  mdi-angularjs 
𧻓  mdi-animation 
  mdi-apple 
  mdi-apple_finder 
  mdi-apple_ios 
בּ  mdi-apple_keyboard_caps 
גּ  mdi-apple_keyboard_command 
דּ  mdi-apple_keyboard_control 
הּ  mdi-apple_keyboard_option 
וּ  mdi-apple_keyboard_shift 
  mdi-apple_mobileme 
  mdi-apple_safari 
ﬓ  mdi-application 
ﲏ  mdi-approval 
  mdi-apps 
  mdi-archive 
  mdi-arrange_bring_forward 
  mdi-arrange_bring_to_front 
  mdi-arrange_send_backward 
  mdi-arrange_send_to_back 
  mdi-arrow_all 
  mdi-arrow_bottom_left 
  mdi-arrow_bottom_right 
ﬔ  mdi-arrow_collapse 
  mdi-arrow_collapse_all 
ﲐ  mdi-arrow_collapse_down 
ﲑ  mdi-arrow_collapse_left 
ﲒ  mdi-arrow_collapse_right 
ﲓ  mdi-arrow_collapse_up 
  mdi-arrow_down 
ﰬ  mdi-arrow_down_bold 
ﰭ  mdi-arrow_down_bold_box 
ﰮ  mdi-arrow_down_bold_box_outline 
  mdi-arrow_down_bold_circle 
  mdi-arrow_down_bold_circle_outline 
  mdi-arrow_down_bold_hexagon_outline 
﮾  mdi-arrow_down_box 
  mdi-arrow_down_drop_circle 
  mdi-arrow_down_drop_circle_outline 
  mdi-arrow_down_thick 
ﬕ  mdi-arrow_expand 
  mdi-arrow_expand_all 
ﲔ  mdi-arrow_expand_down 
ﲕ  mdi-arrow_expand_left 
ﲖ  mdi-arrow_expand_right 
ﲗ  mdi-arrow_expand_up 
  mdi-arrow_left 
ﰯ  mdi-arrow_left_bold 
ﰰ  mdi-arrow_left_bold_box 
ﰱ  mdi-arrow_left_bold_box_outline 
  mdi-arrow_left_bold_circle 
  mdi-arrow_left_bold_circle_outline 
  mdi-arrow_left_bold_hexagon_outline 
﮿  mdi-arrow_left_box 
  mdi-arrow_left_drop_circle 
  mdi-arrow_left_drop_circle_outline 
  mdi-arrow_left_thick 
  mdi-arrow_right 
ﰲ  mdi-arrow_right_bold 
ﰳ  mdi-arrow_right_bold_box 
ﰴ  mdi-arrow_right_bold_box_outline 
  mdi-arrow_right_bold_circle 
  mdi-arrow_right_bold_circle_outline 
  mdi-arrow_right_bold_hexagon_outline 
﯀  mdi-arrow_right_box 
  mdi-arrow_right_drop_circle 
  mdi-arrow_right_drop_circle_outline 
  mdi-arrow_right_thick 
  mdi-arrow_top_left 
  mdi-arrow_top_right 
  mdi-arrow_up 
ﰵ  mdi-arrow_up_bold 
ﰶ  mdi-arrow_up_bold_box 
ﰷ  mdi-arrow_up_bold_box_outline 
  mdi-arrow_up_bold_circle 
  mdi-arrow_up_bold_circle_outline 
  mdi-arrow_up_bold_hexagon_outline 
﯁  mdi-arrow_up_box 
  mdi-arrow_up_drop_circle 
  mdi-arrow_up_drop_circle_outline 
  mdi-arrow_up_thick 
ﴁ  mdi-artist 
  mdi-assistant 
﯂  mdi-asterisk 
  mdi-at 
ﴂ  mdi-atlassian 
ﱦ  mdi-atom 
  mdi-attachment 
  mdi-audiobook 
  mdi-auto_fix 
  mdi-auto_upload 
  mdi-autorenew 
  mdi-av_timer 
ﴃ  mdi-azure 
  mdi-baby 
ﮍ  mdi-baby_buggy 
  mdi-backburger 
  mdi-backspace 
  mdi-backup_restore 
ﭳ  mdi-bandcamp 
  mdi-bank 
  mdi-barcode 
  mdi-barcode_scan 
  mdi-barley 
  mdi-barrel 
  mdi-basecamp 
  mdi-basket 
  mdi-basket_fill 
  mdi-basket_unfill 
ﴄ  mdi-basketball 
  mdi-battery 
  mdi-battery_10 
  mdi-battery_20 
  mdi-battery_30 
  mdi-battery_40 
  mdi-battery_50 
  mdi-battery_60 
  mdi-battery_70 
  mdi-battery_80 
  mdi-battery_90 
  mdi-battery_alert 
  mdi-battery_charging 
  mdi-battery_charging_100 
  mdi-battery_charging_20 
  mdi-battery_charging_30 
  mdi-battery_charging_40 
  mdi-battery_charging_60 
  mdi-battery_charging_80 
  mdi-battery_charging_90 
ﴅ  mdi-battery_charging_wireless 
ﴆ  mdi-battery_charging_wireless_10 
ﴇ  mdi-battery_charging_wireless_20 
ﴈ  mdi-battery_charging_wireless_30 
ﴉ  mdi-battery_charging_wireless_40 
ﴊ  mdi-battery_charging_wireless_50 
ﴋ  mdi-battery_charging_wireless_60 
ﴌ  mdi-battery_charging_wireless_70 
ﴍ  mdi-battery_charging_wireless_80 
ﴎ  mdi-battery_charging_wireless_90 
ﴏ  mdi-battery_charging_wireless_alert 
ﴐ  mdi-battery_charging_wireless_outline 
  mdi-battery_minus 
  mdi-battery_negative 
  mdi-battery_outline 
  mdi-battery_plus 
  mdi-battery_positive 
  mdi-battery_unknown 
  mdi-beach 
ﮎ  mdi-beaker 
  mdi-beats 
  mdi-beer 
  mdi-behance 
  mdi-bell 
  mdi-bell_off 
  mdi-bell_outline 
  mdi-bell_plus 
  mdi-bell_ring 
  mdi-bell_ring_outline 
  mdi-bell_sleep 
  mdi-beta 
  mdi-bible 
  mdi-bike 
  mdi-bing 
  mdi-binoculars 
  mdi-bio 
  mdi-biohazard 
  mdi-bitbucket 
ﴑ  mdi-bitcoin 
  mdi-black_mesa 
  mdi-blackberry 
  mdi-blender 
  mdi-blinds 
  mdi-block_helper 
  mdi-blogger 
  mdi-bluetooth 
  mdi-bluetooth_audio 
  mdi-bluetooth_connect 
  mdi-bluetooth_off 
  mdi-bluetooth_settings 
  mdi-bluetooth_transfer 
  mdi-blur 
  mdi-blur_linear 
  mdi-blur_off 
  mdi-blur_radial 
ﮏ  mdi-bomb 
﯃  mdi-bomb_off 
  mdi-bone 
  mdi-book 
齃  mdi-book_minus 
  mdi-book_multiple 
  mdi-book_multiple_variant 
  mdi-book_open 
龎  mdi-book_open_page_variant 
  mdi-book_open_variant 
﫚  mdi-book_plus 
ﲘ  mdi-book_secure 
ﲙ  mdi-book_unsecure 
  mdi-book_variant 
  mdi-bookmark 
  mdi-bookmark_check 
  mdi-bookmark_music 
  mdi-bookmark_outline 
  mdi-bookmark_plus 
  mdi-bookmark_plus_outline 
  mdi-bookmark_remove 
﫛  mdi-boombox 
﯄  mdi-bootstrap 
  mdi-border_all 
  mdi-border_bottom 
  mdi-border_color 
  mdi-border_horizontal 
  mdi-border_inside 
  mdi-border_left 
  mdi-border_none 
  mdi-border_outside 
  mdi-border_right 
  mdi-border_style 
  mdi-border_top 
  mdi-border_vertical 
ﭶ  mdi-bow_tie 
ﬖ  mdi-bowl 
  mdi-bowling 
  mdi-box 
  mdi-box_cutter 
זּ  mdi-box_shadow 
ﬗ  mdi-bridge 
  mdi-briefcase 
  mdi-briefcase_check 
  mdi-briefcase_download 
ﴒ  mdi-briefcase_outline 
  mdi-briefcase_upload 
  mdi-brightness_1 
  mdi-brightness_2 
  mdi-brightness_3 
  mdi-brightness_4 
  mdi-brightness_5 
  mdi-brightness_6 
  mdi-brightness_7 
  mdi-brightness_auto 
  mdi-broom 
  mdi-brush 
﬘  mdi-buffer 
  mdi-bug 
  mdi-bulletin_board 
  mdi-bullhorn 
﫜  mdi-bullseye 
  mdi-bus 
ﲚ  mdi-bus_articulated_end 
ﲛ  mdi-bus_articulated_front 
ﲜ  mdi-bus_double_decker 
ﲝ  mdi-bus_school 
ﲞ  mdi-bus_side 
  mdi-cached 
  mdi-cake 
  mdi-cake_layered 
  mdi-cake_variant 
  mdi-calculator 
  mdi-calendar 
  mdi-calendar_blank 
  mdi-calendar_check 
  mdi-calendar_clock 
  mdi-calendar_multiple 
  mdi-calendar_multiple_check 
  mdi-calendar_plus 
ﮐ  mdi-calendar_question 
ﭷ  mdi-calendar_range 
  mdi-calendar_remove 
  mdi-calendar_text 
  mdi-calendar_today 
  mdi-call_made 
  mdi-call_merge 
  mdi-call_missed 
  mdi-call_received 
  mdi-call_split 
  mdi-camcorder 
  mdi-camcorder_box 
  mdi-camcorder_box_off 
  mdi-camcorder_off 
  mdi-camera 
ﮑ  mdi-camera_burst 
  mdi-camera_enhance 
  mdi-camera_front 
  mdi-camera_front_variant 
ﲟ  mdi-camera_gopro 
  mdi-camera_iris 
ﲠ  mdi-camera_metering_center 
ﲡ  mdi-camera_metering_matrix 
ﲢ  mdi-camera_metering_partial 
ﲣ  mdi-camera_metering_spot 
﫞  mdi-camera_off 
  mdi-camera_party_mode 
  mdi-camera_rear 
  mdi-camera_rear_variant 
  mdi-camera_switch 
  mdi-camera_timer 
ﰸ  mdi-cancel 
﫡  mdi-candle 
  mdi-candycane 
ﲤ  mdi-cannabis 
  mdi-car 
  mdi-car_battery 
  mdi-car_connected 
ﲥ  mdi-car_convertible 
ﲦ  mdi-car_estate 
ﲧ  mdi-car_hatchback 
ﲨ  mdi-car_pickup 
ﲩ  mdi-car_side 
ﲪ  mdi-car_sports 
  mdi-car_wash 
ﲫ  mdi-caravan 
﬷  mdi-cards 
טּ  mdi-cards_outline 
יּ  mdi-cards_playing_outline 
﯅  mdi-cards_variant 
  mdi-carrot 
  mdi-cart 
ﭪ  mdi-cart_off 
  mdi-cart_outline 
  mdi-cart_plus 
  mdi-case_sensitive_alt 
  mdi-cash 
  mdi-cash_100 
  mdi-cash_multiple 
  mdi-cash_usd 
  mdi-cast 
  mdi-cast_connected 
ﲈ  mdi-cast_off 
  mdi-castle 
  mdi-cat 
ﲬ  mdi-cctv 
ﱧ  mdi-ceiling_light 
  mdi-cellphone 
  mdi-cellphone_android 
  mdi-cellphone_basic 
  mdi-cellphone_dock 
  mdi-cellphone_iphone 
  mdi-cellphone_link 
  mdi-cellphone_link_off 
  mdi-cellphone_settings 
ﴓ  mdi-cellphone_wireless 
  mdi-certificate 
  mdi-chair_school 
  mdi-chart_arc 
  mdi-chart_areaspline 
  mdi-chart_bar 
ﱨ  mdi-chart_bar_stacked 
﫢  mdi-chart_bubble 
ﲭ  mdi-chart_donut 
ﲮ  mdi-chart_donut_variant 
ﭫ  mdi-chart_gantt 
  mdi-chart_histogram 
  mdi-chart_line 
ﱩ  mdi-chart_line_stacked 
ﲯ  mdi-chart_line_variant 
  mdi-chart_pie 
ﭬ  mdi-chart_scatterplot_hexbin 
ﭭ  mdi-chart_timeline 
  mdi-check 
  mdi-check_all 
﫟  mdi-check_circle 
﫠  mdi-check_circle_outline 
  mdi-checkbox_blank 
  mdi-checkbox_blank_circle 
  mdi-checkbox_blank_circle_outline 
  mdi-checkbox_blank_outline 
  mdi-checkbox_marked 
  mdi-checkbox_marked_circle 
  mdi-checkbox_marked_circle_outline 
  mdi-checkbox_marked_outline 
  mdi-checkbox_multiple_blank 
ךּ  mdi-checkbox_multiple_blank_circle 
כּ  mdi-checkbox_multiple_blank_circle_outline 
  mdi-checkbox_multiple_blank_outline 
  mdi-checkbox_multiple_marked 
לּ  mdi-checkbox_multiple_marked_circle 
﬽  mdi-checkbox_multiple_marked_circle_outline 
  mdi-checkbox_multiple_marked_outline 
  mdi-checkerboard 
  mdi-chemical_weapon 
  mdi-chevron_double_down 
  mdi-chevron_double_left 
  mdi-chevron_double_right 
  mdi-chevron_double_up 
  mdi-chevron_down 
  mdi-chevron_left 
  mdi-chevron_right 
  mdi-chevron_up 
ﲰ  mdi-chili_hot 
ﲱ  mdi-chili_medium 
ﲲ  mdi-chili_mild 
﬙  mdi-chip 
  mdi-church 
ﱣ  mdi-circle 
ﱤ  mdi-circle_outline 
  mdi-cisco_webex 
  mdi-city 
  mdi-clipboard 
  mdi-clipboard_account 
  mdi-clipboard_alert 
  mdi-clipboard_arrow_down 
  mdi-clipboard_arrow_left 
  mdi-clipboard_check 
﯆  mdi-clipboard_flow 
  mdi-clipboard_outline 
ﱏ  mdi-clipboard_plus 
  mdi-clipboard_text 
  mdi-clippy 
  mdi-clock 
鬒  mdi-clock_alert 
  mdi-clock_end 
  mdi-clock_fast 
  mdi-clock_in 
  mdi-clock_out 
  mdi-clock_start 
  mdi-close 
  mdi-close_box 
  mdi-close_box_outline 
  mdi-close_circle 
  mdi-close_circle_outline 
  mdi-close_network 
  mdi-close_octagon 
  mdi-close_octagon_outline 
﯇  mdi-close_outline 
  mdi-closed_caption 
  mdi-cloud 
ﲳ  mdi-cloud_braces 
  mdi-cloud_check 
  mdi-cloud_circle 
  mdi-cloud_download 
  mdi-cloud_off_outline 
  mdi-cloud_outline 
  mdi-cloud_print 
  mdi-cloud_print_outline 
מּ  mdi-cloud_sync 
ﲴ  mdi-cloud_tags 
  mdi-cloud_upload 
ﴔ  mdi-clover 
  mdi-code_array 
  mdi-code_braces 
  mdi-code_brackets 
  mdi-code_equal 
  mdi-code_greater_than 
  mdi-code_greater_than_or_equal 
  mdi-code_less_than 
  mdi-code_less_than_or_equal 
  mdi-code_not_equal 
  mdi-code_not_equal_variant 
  mdi-code_parentheses 
  mdi-code_string 
  mdi-code_tags 
ﮒ  mdi-code_tags_check 
  mdi-codepen 
  mdi-coffee 
﯈  mdi-coffee_outline 
  mdi-coffee_to_go 
  mdi-coin 
ﮓ  mdi-coins 
﬿  mdi-collage 
  mdi-color_helper 
  mdi-comment 
  mdi-comment_account 
  mdi-comment_account_outline 
  mdi-comment_alert 
  mdi-comment_alert_outline 
  mdi-comment_check 
  mdi-comment_check_outline 
  mdi-comment_multiple_outline 
  mdi-comment_outline 
  mdi-comment_plus_outline 
  mdi-comment_processing 
  mdi-comment_processing_outline 
ﴕ  mdi-comment_question 
  mdi-comment_question_outline 
﫝  mdi-comment_remove 
  mdi-comment_remove_outline 
  mdi-comment_text 
  mdi-comment_text_outline 
  mdi-compare 
  mdi-compass 
  mdi-compass_outline 
  mdi-console 
ﲵ  mdi-console_line 
  mdi-contact_mail 
﯉  mdi-contacts 
  mdi-content_copy 
  mdi-content_cut 
  mdi-content_duplicate 
  mdi-content_paste 
  mdi-content_save 
  mdi-content_save_all 
ﴖ  mdi-content_save_outline 
﬚  mdi-content_save_settings 
  mdi-contrast 
  mdi-contrast_box 
  mdi-contrast_circle 
  mdi-cookie 
﫥  mdi-copyright 
ﲶ  mdi-corn 
  mdi-counter 
  mdi-cow 
  mdi-creation 
  mdi-credit_card 
  mdi-credit_card_multiple 
﫣  mdi-credit_card_off 
ﭴ  mdi-credit_card_plus 
  mdi-credit_card_scan 
  mdi-crop 
  mdi-crop_free 
  mdi-crop_landscape 
  mdi-crop_portrait 
ﮔ  mdi-crop_rotate 
  mdi-crop_square 
  mdi-crosshairs 
  mdi-crosshairs_gps 
  mdi-crown 
  mdi-cube 
  mdi-cube_outline 
  mdi-cube_send 
  mdi-cube_unfolded 
  mdi-cup 
﫤  mdi-cup_off 
  mdi-cup_water 
  mdi-currency_btc 
ﲷ  mdi-currency_chf 
ﲸ  mdi-currency_cny 
ﲹ  mdi-currency_eth 
  mdi-currency_eur 
  mdi-currency_gbp 
  mdi-currency_inr 
ﲺ  mdi-currency_jpy 
ﲻ  mdi-currency_krw 
  mdi-currency_ngn 
  mdi-currency_rub 
ﲼ  mdi-currency_sign 
  mdi-currency_try 
ﲽ  mdi-currency_twd 
  mdi-currency_usd 
ﭸ  mdi-currency_usd_off 
  mdi-cursor_default 
  mdi-cursor_default_outline 
  mdi-cursor_move 
  mdi-cursor_pointer 
﫦  mdi-cursor_text 
  mdi-database 
  mdi-database_minus 
  mdi-database_plus 
  mdi-debug_step_into 
  mdi-debug_step_out 
  mdi-debug_step_over 
ﱪ  mdi-decagram 
ﱫ  mdi-decagram_outline 
  mdi-decimal_decrease 
  mdi-decimal_increase 
  mdi-delete 
ﮁ  mdi-delete_circle 
﯊  mdi-delete_empty 
﫧  mdi-delete_forever 
ﴗ  mdi-delete_restore 
﫨  mdi-delete_sweep 
  mdi-delete_variant 
  mdi-delta 
  mdi-deskphone 
ﲾ  mdi-desktop_classic 
  mdi-desktop_mac 
  mdi-desktop_tower 
  mdi-details 
ﮕ  mdi-developer_board 
  mdi-deviantart 
﬛  mdi-dialpad 
  mdi-diamond 
  mdi-dice_1 
  mdi-dice_2 
  mdi-dice_3 
  mdi-dice_4 
  mdi-dice_5 
  mdi-dice_6 
ﱭ  mdi-dice_d10 
﫩  mdi-dice_d20 
﫪  mdi-dice_d4 
﫫  mdi-dice_d6 
﫬  mdi-dice_d8 
ﱬ  mdi-dice_multiple 
﬜  mdi-dictionary 
ﲿ  mdi-dip_switch 
  mdi-directions 
נּ  mdi-directions_fork 
ﭮ  mdi-discord 
﫭  mdi-disk 
  mdi-disk_alert 
  mdi-disqus 
  mdi-disqus_outline 
  mdi-division 
  mdi-division_box 
ﮂ  mdi-dna 
  mdi-dns 
ﮖ  mdi-do_not_disturb 
ﮗ  mdi-do_not_disturb_off 
ﮱ  mdi-dolby 
  mdi-domain 
ﳀ  mdi-donkey 
ﴘ  mdi-door 
ﴙ  mdi-door_closed 
ﴚ  mdi-door_open 
  mdi-dots_horizontal 
ﳁ  mdi-dots_horizontal_circle 
  mdi-dots_vertical 
ﳂ  mdi-dots_vertical_circle 
ﮘ  mdi-douban 
  mdi-download 
ﯲ  mdi-download_network 
  mdi-drag 
  mdi-drag_horizontal 
  mdi-drag_vertical 
  mdi-drawing 
  mdi-drawing_box 
  mdi-dribbble 
  mdi-dribbble_box 
  mdi-drone 
  mdi-dropbox 
  mdi-drupal 
  mdi-duck 
  mdi-dumbbell 
ﳃ  mdi-ear_hearing 
  mdi-earth 
﯋  mdi-earth_box 
﯌  mdi-earth_box_off 
  mdi-earth_off 
  mdi-edge 
  mdi-eject 
ﳄ  mdi-elephant 
  mdi-elevation_decline 
  mdi-elevation_rise 
  mdi-elevator 
  mdi-email 
﯍  mdi-email_alert 
  mdi-email_open 
﫮  mdi-email_open_outline 
  mdi-email_outline 
  mdi-email_secure 
﫯  mdi-email_variant 
﮲  mdi-emby 
  mdi-emoticon 
  mdi-emoticon_cool 
ﮙ  mdi-emoticon_dead 
  mdi-emoticon_devil 
ﮚ  mdi-emoticon_excited 
  mdi-emoticon_happy 
  mdi-emoticon_neutral 
  mdi-emoticon_poop 
  mdi-emoticon_sad 
  mdi-emoticon_tongue 
  mdi-engine 
  mdi-engine_outline 
  mdi-equal 
  mdi-equal_box 
  mdi-eraser 
סּ  mdi-eraser_variant 
  mdi-escalator 
  mdi-ethernet 
  mdi-ethernet_cable 
  mdi-ethernet_cable_off 
  mdi-etsy 
﫰  mdi-ev_station 
ﳅ  mdi-eventbrite 
  mdi-evernote 
  mdi-exclamation 
  mdi-exit_to_app 
  mdi-export 
  mdi-eye 
  mdi-eye_off 
﯏  mdi-eye_off_outline 
﯎  mdi-eye_outline 
  mdi-eyedropper 
  mdi-eyedropper_variant 
﭂  mdi-face 
ףּ  mdi-face_profile 
  mdi-facebook 
  mdi-facebook_box 
  mdi-facebook_messenger 
  mdi-factory 
  mdi-fan 
ﴛ  mdi-fan_off 
  mdi-fast_forward 
﯐  mdi-fast_forward_outline 
  mdi-fax 
﯑  mdi-feather 
  mdi-ferry 
  mdi-file 
ﰹ  mdi-file_account 
  mdi-file_chart 
  mdi-file_check 
  mdi-file_cloud 
  mdi-file_delimited 
  mdi-file_document 
  mdi-file_document_box 
  mdi-file_excel 
  mdi-file_excel_box 
  mdi-file_export 
  mdi-file_find 
﬒  mdi-file_hidden 
  mdi-file_image 
  mdi-file_import 
  mdi-file_lock 
  mdi-file_multiple 
  mdi-file_music 
  mdi-file_outline 
  mdi-file_pdf 
  mdi-file_pdf_box 
ﴜ  mdi-file_percent 
ﱐ  mdi-file_plus 
  mdi-file_powerpoint 
  mdi-file_powerpoint_box 
  mdi-file_presentation_box 
ﭯ  mdi-file_restore 
  mdi-file_send 
פּ  mdi-file_tree 
  mdi-file_video 
  mdi-file_word 
  mdi-file_word_box 
  mdi-file_xml 
  mdi-film 
  mdi-filmstrip 
  mdi-filmstrip_off 
  mdi-filter 
  mdi-filter_outline 
  mdi-filter_remove 
  mdi-filter_remove_outline 
  mdi-filter_variant 
ﴝ  mdi-finance 
﯒  mdi-find_replace 
  mdi-fingerprint 
  mdi-fire 
  mdi-firefox 
  mdi-fish 
  mdi-flag 
  mdi-flag_checkered 
  mdi-flag_outline 
  mdi-flag_triangle 
  mdi-flag_variant 
  mdi-flag_variant_outline 
  mdi-flash 
  mdi-flash_auto 
ﴞ  mdi-flash_circle 
  mdi-flash_off 
ﯓ  mdi-flash_outline 
ﭹ  mdi-flash_red_eye 
  mdi-flashlight 
  mdi-flashlight_off 
  mdi-flask 
  mdi-flask_empty 
  mdi-flask_empty_outline 
  mdi-flask_outline 
  mdi-flattr 
  mdi-flip_to_back 
  mdi-flip_to_front 
ﴟ  mdi-floor_plan 
  mdi-floppy 
  mdi-flower 
  mdi-folder 
  mdi-folder_account 
  mdi-folder_download 
  mdi-folder_google_drive 
  mdi-folder_image 
  mdi-folder_lock 
  mdi-folder_lock_open 
  mdi-folder_move 
  mdi-folder_multiple 
  mdi-folder_multiple_image 
  mdi-folder_multiple_outline 
ﱮ  mdi-folder_open 
  mdi-folder_outline 
  mdi-folder_plus 
  mdi-folder_remove 
ﮛ  mdi-folder_star 
  mdi-folder_upload 
  mdi-font_awesome 
  mdi-food 
  mdi-food_apple 
ﳆ  mdi-food_croissant 
﫱  mdi-food_fork_drink 
﫲  mdi-food_off 
  mdi-food_variant 
  mdi-football 
  mdi-football_australian 
  mdi-football_helmet 
ﳇ  mdi-forklift 
ﱑ  mdi-format_align_bottom 
  mdi-format_align_center 
  mdi-format_align_justify 
  mdi-format_align_left 
ﱒ  mdi-format_align_middle 
  mdi-format_align_right 
ﱓ  mdi-format_align_top 
﭅  mdi-format_annotation_plus 
  mdi-format_bold 
  mdi-format_clear 
  mdi-format_color_fill 
ﮜ  mdi-format_color_text 
  mdi-format_float_center 
  mdi-format_float_left 
  mdi-format_float_none 
  mdi-format_float_right 
ﯔ  mdi-format_font 
  mdi-format_header_1 
  mdi-format_header_2 
  mdi-format_header_3 
  mdi-format_header_4 
  mdi-format_header_5 
  mdi-format_header_6 
  mdi-format_header_decrease 
  mdi-format_header_equal 
  mdi-format_header_increase 
  mdi-format_header_pound 
יִ  mdi-format_horizontal_align_center 
ﬞ  mdi-format_horizontal_align_left 
ײַ  mdi-format_horizontal_align_right 
  mdi-format_indent_decrease 
  mdi-format_indent_increase 
  mdi-format_italic 
  mdi-format_line_spacing 
難  mdi-format_line_style 
靖  mdi-format_line_weight 
  mdi-format_list_bulleted 
  mdi-format_list_bulleted_type 
ﱔ  mdi-format_list_checks 
  mdi-format_list_numbers 
ﯕ  mdi-format_page_break 
  mdi-format_paint 
  mdi-format_paragraph 
ﯖ  mdi-format_pilcrow 
  mdi-format_quote_close 
ﱕ  mdi-format_quote_open 
ﮨ  mdi-format_rotate_90 
ﮝ  mdi-format_section 
  mdi-format_size 
  mdi-format_strikethrough 
  mdi-format_strikethrough_variant 
  mdi-format_subscript 
  mdi-format_superscript 
  mdi-format_text 
  mdi-format_textdirection_l_to_r 
  mdi-format_textdirection_r_to_l 
﫳  mdi-format_title 
  mdi-format_underline 
ﬠ  mdi-format_vertical_align_bottom 
ﬡ  mdi-format_vertical_align_center 
ﬢ  mdi-format_vertical_align_top 
  mdi-format_wrap_inline 
  mdi-format_wrap_square 
  mdi-format_wrap_tight 
  mdi-format_wrap_top_bottom 
  mdi-forum 
ﴠ  mdi-forum_outline 
  mdi-forward 
  mdi-foursquare 
  mdi-fridge 
  mdi-fridge_filled 
  mdi-fridge_filled_bottom 
  mdi-fridge_filled_top 
ﳈ  mdi-fuel 
  mdi-fullscreen 
  mdi-fullscreen_exit 
  mdi-function 
  mdi-gamepad 
  mdi-gamepad_variant 
ﯗ  mdi-garage 
ﯘ  mdi-garage_open 
צּ  mdi-gas_cylinder 
  mdi-gas_station 
  mdi-gate 
  mdi-gauge 
  mdi-gavel 
  mdi-gender_female 
  mdi-gender_male 
  mdi-gender_male_female 
  mdi-gender_transgender 
ﳉ  mdi-gesture 
ﰺ  mdi-gesture_double_tap 
ﰻ  mdi-gesture_swipe_down 
ﰼ  mdi-gesture_swipe_left 
ﰽ  mdi-gesture_swipe_right 
ﰾ  mdi-gesture_swipe_up 
ﰿ  mdi-gesture_tap 
ﱀ  mdi-gesture_two_double_tap 
ﱁ  mdi-gesture_two_tap 
  mdi-ghost 
  mdi-gift 
  mdi-git 
  mdi-github_box 
  mdi-github_circle 
ﯙ  mdi-github_face 
  mdi-glass_flute 
  mdi-glass_mug 
  mdi-glass_stange 
  mdi-glass_tulip 
  mdi-glassdoor 
  mdi-glasses 
  mdi-gmail 
  mdi-gnome 
ﴡ  mdi-golf 
ﮄ  mdi-gondola 
  mdi-google 
ﳊ  mdi-google_analytics 
ﳋ  mdi-google_assistant 
  mdi-google_cardboard 
  mdi-google_chrome 
  mdi-google_circles 
  mdi-google_circles_communities 
  mdi-google_circles_extended 
  mdi-google_circles_group 
  mdi-google_controller 
  mdi-google_controller_off 
  mdi-google_drive 
  mdi-google_earth 
  mdi-google_glass 
ﴢ  mdi-google_home 
ﯚ  mdi-google_keep 
﫴  mdi-google_maps 
  mdi-google_nearby 
  mdi-google_pages 
ﯛ  mdi-google_photos 
  mdi-google_physical_web 
  mdi-google_play 
  mdi-google_plus 
  mdi-google_plus_box 
  mdi-google_translate 
  mdi-google_wallet 
ﮞ  mdi-gradient 
קּ  mdi-grease_pencil 
  mdi-grid 
ﱖ  mdi-grid_large 
  mdi-grid_off 
  mdi-group 
ﱯ  mdi-guitar_acoustic 
  mdi-guitar_electric 
  mdi-guitar_pick 
  mdi-guitar_pick_outline 
ﴣ  mdi-guy_fawkes_mask 
ﬣ  mdi-hackernews 
ﮃ  mdi-hamburger 
  mdi-hand_pointing_right 
  mdi-hanger 
  mdi-hangouts 
  mdi-harddisk 
  mdi-headphones 
  mdi-headphones_box 
ﳌ  mdi-headphones_off 
  mdi-headphones_settings 
  mdi-headset 
  mdi-headset_dock 
  mdi-headset_off 
  mdi-heart 
  mdi-heart_box 
  mdi-heart_box_outline 
  mdi-heart_broken 
ﯝ  mdi-heart_half 
ﯜ  mdi-heart_half_full 
ﯞ  mdi-heart_half_outline 
ﱗ  mdi-heart_off 
  mdi-heart_outline 
﫵  mdi-heart_pulse 
  mdi-help 
ﲉ  mdi-help_box 
  mdi-help_circle 
ﬤ  mdi-help_circle_outline 
ﯳ  mdi-help_network 
  mdi-hexagon 
ﯟ  mdi-hexagon_multiple 
  mdi-hexagon_outline 
ﳍ  mdi-high_definition 
﫶  mdi-highway 
  mdi-history 
  mdi-hololens 
  mdi-home 
ﴤ  mdi-home_account 
ﳎ  mdi-home_assistant 
ﳏ  mdi-home_automation 
ﳐ  mdi-home_circle 
ﴥ  mdi-home_heart 
﫷  mdi-home_map_marker 
  mdi-home_modern 
ﮟ  mdi-home_outline 
  mdi-home_variant 
ﯠ  mdi-hook 
ﯡ  mdi-hook_off 
  mdi-hops 
  mdi-hospital 
  mdi-hospital_building 
  mdi-hospital_marker 
ﴦ  mdi-hot_tub 
  mdi-hotel 
  mdi-houzz 
  mdi-houzz_box 
ﴧ  mdi-hulu 
  mdi-human 
  mdi-human_child 
רּ  mdi-human_female 
שּ  mdi-human_greeting 
תּ  mdi-human_handsdown 
וֹ  mdi-human_handsup 
בֿ  mdi-human_male 
  mdi-human_male_female 
龜  mdi-human_pregnant 
ﱂ  mdi-humble_bundle 
ﴨ  mdi-ice_cream 
  mdi-image 
  mdi-image_album 
  mdi-image_area 
  mdi-image_area_close 
  mdi-image_broken 
  mdi-image_broken_variant 
  mdi-image_filter 
  mdi-image_filter_black_white 
  mdi-image_filter_center_focus 
  mdi-image_filter_center_focus_weak 
  mdi-image_filter_drama 
  mdi-image_filter_frames 
  mdi-image_filter_hdr 
  mdi-image_filter_none 
  mdi-image_filter_tilt_shift 
  mdi-image_filter_vintage 
  mdi-image_multiple 
ﴩ  mdi-image_off 
  mdi-import 
ﮅ  mdi-inbox 
  mdi-inbox_arrow_down 
  mdi-inbox_arrow_up 
﫸  mdi-incognito 
ﯢ  mdi-infinity 
  mdi-information 
  mdi-information_outline 
כֿ  mdi-information_variant 
  mdi-instagram 
  mdi-instapaper 
  mdi-internet_explorer 
  mdi-invert_colors 
ﭵ  mdi-itunes 
  mdi-jeepney 
  mdi-jira 
  mdi-jsfiddle 
ﬥ  mdi-json 
ﴪ  mdi-karate 
  mdi-keg 
﫹  mdi-kettle 
  mdi-key 
  mdi-key_change 
  mdi-key_minus 
  mdi-key_plus 
  mdi-key_remove 
  mdi-key_variant 
  mdi-keyboard 
  mdi-keyboard_backspace 
  mdi-keyboard_caps 
  mdi-keyboard_close 
  mdi-keyboard_off 
  mdi-keyboard_return 
  mdi-keyboard_tab 
  mdi-keyboard_variant 
ﱃ  mdi-kickstarter 
  mdi-kodi 
  mdi-label 
  mdi-label_outline 
ﴫ  mdi-ladybug 
ﬦ  mdi-lambda 
﮳  mdi-lamp 
  mdi-lan 
  mdi-lan_connect 
  mdi-lan_disconnect 
  mdi-lan_pending 
ﭰ  mdi-language_c 
ﭱ  mdi-language_cpp 
  mdi-language_csharp 
  mdi-language_css3 
ﳑ  mdi-language_go 
  mdi-language_html5 
  mdi-language_javascript 
  mdi-language_php 
  mdi-language_python 
  mdi-language_python_text 
ﳒ  mdi-language_r 
ﯣ  mdi-language_swift 
ﯤ  mdi-language_typescript 
  mdi-laptop 
  mdi-laptop_chromebook 
  mdi-laptop_mac 
ﯥ  mdi-laptop_off 
  mdi-laptop_windows 
  mdi-lastfm 
聾  mdi-lastpass 
  mdi-launch 
ﳓ  mdi-lava_lamp 
  mdi-layers 
  mdi-layers_off 
פֿ  mdi-lead_pencil 
  mdi-leaf 
  mdi-led_off 
  mdi-led_on 
  mdi-led_outline 
ﳔ  mdi-led_strip 
  mdi-led_variant_off 
  mdi-led_variant_on 
  mdi-led_variant_outline 
  mdi-library 
  mdi-library_books 
  mdi-library_music 
  mdi-library_plus 
  mdi-lightbulb 
ﯦ  mdi-lightbulb_on 
ﯧ  mdi-lightbulb_on_outline 
  mdi-lightbulb_outline 
  mdi-link 
  mdi-link_off 
  mdi-link_variant 
  mdi-link_variant_off 
  mdi-linkedin 
  mdi-linkedin_box 
  mdi-linux 
ﱰ  mdi-loading 
  mdi-lock 
  mdi-lock_open 
  mdi-lock_open_outline 
  mdi-lock_outline 
ﯨ  mdi-lock_pattern 
﫺  mdi-lock_plus 
ﱱ  mdi-lock_reset 
ﳕ  mdi-locker 
ﳖ  mdi-locker_multiple 
  mdi-login 
﫻  mdi-login_variant 
  mdi-logout 
﫼  mdi-logout_variant 
  mdi-looks 
ﯩ  mdi-loop 
  mdi-loupe 
  mdi-lumx 
  mdi-magnet 
  mdi-magnet_on 
  mdi-magnify 
  mdi-magnify_minus 
ﯪ  mdi-magnify_minus_outline 
  mdi-magnify_plus 
ﯫ  mdi-magnify_plus_outline 
  mdi-mail_ru 
ﯬ  mdi-mailbox 
  mdi-map 
  mdi-map_marker 
  mdi-map_marker_circle 
ﭏ  mdi-map_marker_minus 
  mdi-map_marker_multiple 
  mdi-map_marker_off 
ﳗ  mdi-map_marker_outline 
ﭐ  mdi-map_marker_plus 
  mdi-map_marker_radius 
  mdi-margin 
  mdi-markdown 
ﭑ  mdi-marker 
  mdi-marker_check 
  mdi-martini 
  mdi-material_ui 
  mdi-math_compass 
ﬧ  mdi-matrix 
  mdi-maxcdn 
ﯭ  mdi-medical_bag 
  mdi-medium 
  mdi-memory 
  mdi-menu 
  mdi-menu_down 
﮴  mdi-menu_down_outline 
  mdi-menu_left 
  mdi-menu_right 
  mdi-menu_up 
﮵  mdi-menu_up_outline 
  mdi-message 
  mdi-message_alert 
ﮠ  mdi-message_bulleted 
ﮡ  mdi-message_bulleted_off 
  mdi-message_draw 
  mdi-message_image 
  mdi-message_outline 
ﭒ  mdi-message_plus 
  mdi-message_processing 
  mdi-message_reply 
  mdi-message_reply_text 
ﯮ  mdi-message_settings 
ﯯ  mdi-message_settings_variant 
  mdi-message_text 
  mdi-message_text_outline 
  mdi-message_video 
ﬨ  mdi-meteor 
ﳘ  mdi-metronome 
ﳙ  mdi-metronome_tick 
ﳚ  mdi-micro_sd 
  mdi-microphone 
  mdi-microphone_off 
  mdi-microphone_outline 
  mdi-microphone_settings 
  mdi-microphone_variant 
  mdi-microphone_variant_off 
ﭓ  mdi-microscope 
  mdi-microsoft 
  mdi-minecraft 
  mdi-minus 
  mdi-minus_box 
ﯰ  mdi-minus_box_outline 
  mdi-minus_circle 
  mdi-minus_circle_outline 
  mdi-minus_network 
﬩  mdi-mixcloud 
ﳛ  mdi-mixer 
  mdi-monitor 
  mdi-monitor_multiple 
  mdi-more 
  mdi-motorbike 
  mdi-mouse 
  mdi-mouse_off 
  mdi-mouse_variant 
  mdi-mouse_variant_off 
ﭔ  mdi-move_resize 
ﭕ  mdi-move_resize_variant 
  mdi-movie 
ﳜ  mdi-movie_roll 
  mdi-multiplication 
  mdi-multiplication_box 
ﳝ  mdi-mushroom 
ﳞ  mdi-mushroom_outline 
ﱘ  mdi-music 
  mdi-music_box 
  mdi-music_box_outline 
  mdi-music_circle 
  mdi-music_note 
﫽  mdi-music_note_bluetooth 
﫾  mdi-music_note_bluetooth_off 
  mdi-music_note_eighth 
  mdi-music_note_half 
  mdi-music_note_off 
  mdi-music_note_quarter 
  mdi-music_note_sixteenth 
  mdi-music_note_whole 
ﱙ  mdi-music_off 
  mdi-nature 
  mdi-nature_people 
  mdi-navigation 
頻  mdi-near_me 
  mdi-needle 
  mdi-nest_protect 
  mdi-nest_thermostat 
ﱄ  mdi-netflix 
ﯱ  mdi-network 
  mdi-new_box 
  mdi-newspaper 
  mdi-nfc 
  mdi-nfc_tap 
  mdi-nfc_variant 
ﱲ  mdi-ninja 
ﳟ  mdi-nintendo_switch 
  mdi-nodejs 
  mdi-note 
﮶  mdi-note_multiple 
﮷  mdi-note_multiple_outline 
  mdi-note_outline 
  mdi-note_plus 
  mdi-note_plus_outline 
  mdi-note_text 
ﴬ  mdi-notebook 
  mdi-notification_clear_all 
ﯵ  mdi-npm 
ﮢ  mdi-nuke 
ﳠ  mdi-null 
  mdi-numeric 
  mdi-numeric_0_box 
  mdi-numeric_0_box_multiple_outline 
  mdi-numeric_0_box_outline 
  mdi-numeric_1_box 
  mdi-numeric_1_box_multiple_outline 
  mdi-numeric_1_box_outline 
  mdi-numeric_2_box 
  mdi-numeric_2_box_multiple_outline 
  mdi-numeric_2_box_outline 
  mdi-numeric_3_box 
  mdi-numeric_3_box_multiple_outline 
  mdi-numeric_3_box_outline 
  mdi-numeric_4_box 
  mdi-numeric_4_box_multiple_outline 
  mdi-numeric_4_box_outline 
  mdi-numeric_5_box 
  mdi-numeric_5_box_multiple_outline 
  mdi-numeric_5_box_outline 
  mdi-numeric_6_box 
  mdi-numeric_6_box_multiple_outline 
  mdi-numeric_6_box_outline 
  mdi-numeric_7_box 
  mdi-numeric_7_box_multiple_outline 
  mdi-numeric_7_box_outline 
  mdi-numeric_8_box 
  mdi-numeric_8_box_multiple_outline 
  mdi-numeric_8_box_outline 
  mdi-numeric_9_box 
  mdi-numeric_9_box_multiple_outline 
  mdi-numeric_9_box_outline 
  mdi-numeric_9_plus_box 
  mdi-numeric_9_plus_box_multiple_outline 
  mdi-numeric_9_plus_box_outline 
ﯶ  mdi-nut 
  mdi-nutrition 
ﭺ  mdi-oar 
  mdi-octagon 
  mdi-octagon_outline 
ﯷ  mdi-octagram 
ﱳ  mdi-octagram_outline 
  mdi-odnoklassniki 
  mdi-office 
  mdi-oil 
  mdi-oil_temperature 
  mdi-omega 
  mdi-onedrive 
ﱅ  mdi-onenote 
頋  mdi-opacity 
  mdi-open_in_app 
  mdi-open_in_new 
  mdi-openid 
  mdi-opera 
  mdi-orbit 
  mdi-ornament 
  mdi-ornament_variant 
  mdi-owl 
  mdi-package 
  mdi-package_down 
  mdi-package_up 
  mdi-package_variant 
  mdi-package_variant_closed 
﫿  mdi-page_first 
ﬀ  mdi-page_last 
ﯸ  mdi-page_layout_body 
ﯹ  mdi-page_layout_footer 
ﯺ  mdi-page_layout_header 
ﯻ  mdi-page_layout_sidebar_left 
ﯼ  mdi-page_layout_sidebar_right 
  mdi-palette 
  mdi-palette_advanced 
  mdi-panda 
  mdi-pandora 
  mdi-panorama 
  mdi-panorama_fisheye 
  mdi-panorama_horizontal 
  mdi-panorama_vertical 
  mdi-panorama_wide_angle 
  mdi-paper_cut_vertical 
  mdi-paperclip 
  mdi-parking 
ﳡ  mdi-passport 
  mdi-pause 
  mdi-pause_circle 
  mdi-pause_circle_outline 
  mdi-pause_octagon 
  mdi-pause_octagon_outline 
  mdi-paw 
ﭖ  mdi-paw_off 
  mdi-pen 
  mdi-pencil 
  mdi-pencil_box 
  mdi-pencil_box_outline 
ﯽ  mdi-pencil_circle 
ﱴ  mdi-pencil_circle_outline 
  mdi-pencil_lock 
  mdi-pencil_off 
ﯾ  mdi-pentagon 
ﯿ  mdi-pentagon_outline 
  mdi-percent 
ﳢ  mdi-periodic_table_co2 
ﱆ  mdi-periscope 
  mdi-pharmacy 
  mdi-phone 
  mdi-phone_bluetooth 
ﬁ  mdi-phone_classic 
  mdi-phone_forward 
  mdi-phone_hangup 
  mdi-phone_in_talk 
  mdi-phone_incoming 
  mdi-phone_locked 
  mdi-phone_log 
ﭗ  mdi-phone_minus 
  mdi-phone_missed 
  mdi-phone_outgoing 
  mdi-phone_paused 
ﭘ  mdi-phone_plus 
ﴭ  mdi-phone_return 
  mdi-phone_settings 
  mdi-phone_voip 
  mdi-pi 
  mdi-pi_box 
ﭻ  mdi-piano 
豈  mdi-pig 
更  mdi-pill 
ﰀ  mdi-pillar 
車  mdi-pin 
賈  mdi-pin_off 
滑  mdi-pine_tree 
串  mdi-pine_tree_box 
句  mdi-pinterest 
龜  mdi-pinterest_box 
ﳣ  mdi-pipe 
ﳤ  mdi-pipe_disconnected 
ﰁ  mdi-pistol 
龜  mdi-pizza 
﮹  mdi-plane_shield 
契  mdi-play 
金  mdi-play_box_outline 
喇  mdi-play_circle 
奈  mdi-play_circle_outline 
懶  mdi-play_pause 
癩  mdi-play_protected_content 
陼  mdi-playlist_check 
羅  mdi-playlist_minus 
蘿  mdi-playlist_play 
螺  mdi-playlist_plus 
裸  mdi-playlist_remove 
邏  mdi-playstation 
﮸  mdi-plex 
樂  mdi-plus 
洛  mdi-plus_box 
ﰂ  mdi-plus_box_outline 
烙  mdi-plus_circle 
珞  mdi-plus_circle_multiple_outline 
落  mdi-plus_circle_outline 
酪  mdi-plus_network 
駱  mdi-plus_one 
ﰃ  mdi-plus_outline 
亂  mdi-pocket 
卵  mdi-pokeball 
ﴮ  mdi-poker_chip 
欄  mdi-polaroid 
爛  mdi-poll 
蘭  mdi-poll_box 
鸞  mdi-polymer 
ﬅ  mdi-pool 
嵐  mdi-popcorn 
ﭙ  mdi-pot 
ﭚ  mdi-pot_mix 
濫  mdi-pound 
藍  mdi-pound_box 
襤  mdi-power 
ﮣ  mdi-power_plug 
ﮤ  mdi-power_plug_off 
拉  mdi-power_settings 
臘  mdi-power_socket 
ﳥ  mdi-power_socket_eu 
ﳦ  mdi-power_socket_uk 
ﳧ  mdi-power_socket_us 
ﰄ  mdi-prescription 
蠟  mdi-presentation 
廊  mdi-presentation_play 
朗  mdi-printer 
浪  mdi-printer_3d 
狼  mdi-printer_alert 
ﰅ  mdi-printer_settings 
ﬂ  mdi-priority_high 
ﬃ  mdi-priority_low 
郎  mdi-professional_hexagon 
來  mdi-projector 
冷  mdi-projector_screen 
ﮥ  mdi-publish 
勞  mdi-pulse 
擄  mdi-puzzle 
ﬄ  mdi-qqchat 
櫓  mdi-qrcode 
爐  mdi-qrcode_scan 
盧  mdi-quadcopter 
老  mdi-quality_high 
蘆  mdi-quicktime 
虜  mdi-radar 
路  mdi-radiator 
露  mdi-radio 
魯  mdi-radio_handheld 
鷺  mdi-radio_tower 
碌  mdi-radioactive 
祿  mdi-radiobox_blank 
綠  mdi-radiobox_marked 
菉  mdi-raspberrypi 
錄  mdi-ray_end 
鹿  mdi-ray_end_arrow 
論  mdi-ray_start 
壟  mdi-ray_start_arrow 
弄  mdi-ray_start_end 
籠  mdi-ray_vertex 
ﰆ  mdi-react 
牢  mdi-read 
賂  mdi-receipt 
雷  mdi-record 
壘  mdi-record_rec 
屢  mdi-recycle 
樓  mdi-reddit 
淚  mdi-redo 
漏  mdi-redo_variant 
累  mdi-refresh 
縷  mdi-regex 
陋  mdi-relative_scale 
勒  mdi-reload 
肋  mdi-remote 
凜  mdi-rename_box 
ﮆ  mdi-reorder_horizontal 
ﮇ  mdi-reorder_vertical 
凌  mdi-repeat 
稜  mdi-repeat_off 
綾  mdi-repeat_once 
菱  mdi-replay 
陵  mdi-reply 
讀  mdi-reply_all 
拏  mdi-reproduction 
樂  mdi-resize_bottom_right 
諾  mdi-responsive 
ﰇ  mdi-restart 
ﮦ  mdi-restore 
丹  mdi-rewind 
ﰈ  mdi-rewind_outline 
ﰉ  mdi-rhombus 
ﰊ  mdi-rhombus_outline 
寧  mdi-ribbon 
ﳨ  mdi-rice 
ﳩ  mdi-ring 
怒  mdi-road 
率  mdi-road_variant 
ﮧ  mdi-robot 
異  mdi-rocket 
ﰋ  mdi-roomba 
北  mdi-rotate_3d 
磻  mdi-rotate_left 
便  mdi-rotate_left_variant 
復  mdi-rotate_right 
不  mdi-rotate_right_variant 
ﬆ  mdi-rounded_corner 
泌  mdi-router_wireless 
數  mdi-routes 
﬇  mdi-rowing 
索  mdi-rss 
參  mdi-rss_box 
塞  mdi-ruler 
ﰌ  mdi-run 
省  mdi-run_fast 
葉  mdi-sale 
ﳪ  mdi-sass 
說  mdi-satellite 
殺  mdi-satellite_variant 
﬈  mdi-saxophone 
辰  mdi-scale 
𢡄  mdi-scale_balance 
沈  mdi-scale_bathroom 
ﮩ  mdi-scanner 
拾  mdi-school 
若  mdi-screen_rotation 
掠  mdi-screen_rotation_lock 
略  mdi-screwdriver 
亮  mdi-script 
兩  mdi-sd 
凉  mdi-seal 
ﰍ  mdi-search_web 
梁  mdi-seat_flat 
糧  mdi-seat_flat_angled 
良  mdi-seat_individual_suite 
諒  mdi-seat_legroom_extra 
量  mdi-seat_legroom_normal 
勵  mdi-seat_legroom_reduced 
呂  mdi-seat_recline_extra 
女  mdi-seat_recline_normal 
廬  mdi-security 
ﮈ  mdi-security_home 
旅  mdi-security_network 
濾  mdi-select 
礪  mdi-select_all 
閭  mdi-select_inverse 
驪  mdi-select_off 
麗  mdi-selection 
ﱵ  mdi-selection_off 
黎  mdi-send 
ﳫ  mdi-send_secure 
ﭛ  mdi-serial_port 
力  mdi-server 
曆  mdi-server_minus 
歷  mdi-server_network 
轢  mdi-server_network_off 
年  mdi-server_off 
憐  mdi-server_plus 
戀  mdi-server_remove 
撚  mdi-server_security 
ﱶ  mdi-set_all 
ﱷ  mdi-set_center 
ﱸ  mdi-set_center_right 
ﱹ  mdi-set_left 
ﱺ  mdi-set_left_center 
ﱻ  mdi-set_left_right 
ﱼ  mdi-set_none 
ﱽ  mdi-set_right 
漣  mdi-settings 
煉  mdi-settings_box 
ﴯ  mdi-shape 
ﭜ  mdi-shape_circle_plus 
ﴰ  mdi-shape_outline 
璉  mdi-shape_plus 
ﭝ  mdi-shape_polygon_plus 
ﭞ  mdi-shape_rectangle_plus 
ﭟ  mdi-shape_square_plus 
秊  mdi-share 
練  mdi-share_variant 
聯  mdi-shield 
ﱾ  mdi-shield_half_full 
輦  mdi-shield_outline 
ﴱ  mdi-ship_wheel 
蓮  mdi-shopping 
連  mdi-shopping_music 
ﰎ  mdi-shovel 
ﰏ  mdi-shovel_off 
鍊  mdi-shredder 
列  mdi-shuffle 
劣  mdi-shuffle_disabled 
咽  mdi-shuffle_variant 
烈  mdi-sigma 
שׁ  mdi-sigma_lower 
裂  mdi-sign_caution 
ﱿ  mdi-sign_direction 
ﲀ  mdi-sign_text 
說  mdi-signal 
ﰐ  mdi-signal_2g 
ﰑ  mdi-signal_3g 
ﰒ  mdi-signal_4g 
ﰓ  mdi-signal_hspa 
ﰔ  mdi-signal_hspa_plus 
ﲁ  mdi-signal_off 
﬉  mdi-signal_variant 
廉  mdi-silverware 
念  mdi-silverware_fork 
捻  mdi-silverware_spoon 
殮  mdi-silverware_variant 
簾  mdi-sim 
獵  mdi-sim_alert 
令  mdi-sim_off 
囹  mdi-sitemap 
寧  mdi-skip_backward 
嶺  mdi-skip_forward 
怜  mdi-skip_next 
ﭠ  mdi-skip_next_circle 
ﭡ  mdi-skip_next_circle_outline 
玲  mdi-skip_previous 
ﭢ  mdi-skip_previous_circle 
ﭣ  mdi-skip_previous_circle_outline 
ﮊ  mdi-skull 
瑩  mdi-skype 
羚  mdi-skype_business 
聆  mdi-slack 
鈴  mdi-sleep 
零  mdi-sleep_off 
靈  mdi-smoking 
領  mdi-smoking_off 
例  mdi-snapchat 
ﰕ  mdi-snowflake 
禮  mdi-snowman 
醴  mdi-soccer 
ﴲ  mdi-soccer_field 
隸  mdi-sofa 
ﮋ  mdi-solid 
惡  mdi-sort 
了  mdi-sort_alphabetical 
僚  mdi-sort_ascending 
寮  mdi-sort_descending 
尿  mdi-sort_numeric 
料  mdi-sort_variant 
樂  mdi-soundcloud 
שׂ  mdi-source_branch 
ﰖ  mdi-source_commit 
ﰗ  mdi-source_commit_end 
ﰘ  mdi-source_commit_end_local 
ﰙ  mdi-source_commit_local 
ﰚ  mdi-source_commit_next_local 
ﰛ  mdi-source_commit_start 
ﰜ  mdi-source_commit_start_next_local 
燎  mdi-source_fork 
שּׁ  mdi-source_merge 
療  mdi-source_pull 
ﳬ  mdi-soy_sauce 
蓼  mdi-speaker 
遼  mdi-speaker_off 
ﰝ  mdi-speaker_wireless 
龍  mdi-speedometer 
暈  mdi-spellcheck 
阮  mdi-spotify 
劉  mdi-spotlight 
杻  mdi-spotlight_beam 
ﭤ  mdi-spray 
ﱢ  mdi-square 
柳  mdi-square_inc 
流  mdi-square_inc_cash 
ﱡ  mdi-square_outline 
ﲂ  mdi-square_root 
溜  mdi-stack_overflow 
﬊  mdi-stackexchange 
ﰞ  mdi-stadium 
琉  mdi-stairs 
ﳭ  mdi-standard_definition 
留  mdi-star 
硫  mdi-star_circle 
紐  mdi-star_half 
類  mdi-star_off 
六  mdi-star_outline 
戮  mdi-steam 
陸  mdi-steering 
倫  mdi-step_backward 
崙  mdi-step_backward_2 
淪  mdi-step_forward 
輪  mdi-step_forward_2 
律  mdi-stethoscope 
𢡊  mdi-sticker 
ﲃ  mdi-sticker_emoji 
慄  mdi-stocking 
栗  mdi-stop 
ﭥ  mdi-stop_circle 
ﭦ  mdi-stop_circle_outline 
率  mdi-store 
隆  mdi-store_24_hour 
利  mdi-stove 
﬋  mdi-subdirectory_arrow_left 
﬌  mdi-subdirectory_arrow_right 
ﮪ  mdi-subway 
吏  mdi-subway_variant 
ﲄ  mdi-summit 
履  mdi-sunglasses 
醙  mdi-surround_sound 
ﳮ  mdi-surround_sound_2_0 
ﳯ  mdi-surround_sound_3_1 
ﳰ  mdi-surround_sound_5_1 
ﳱ  mdi-surround_sound_7_1 
ﰟ  mdi-svg 
易  mdi-swap_horizontal 
李  mdi-swap_vertical 
梨  mdi-swim 
泥  mdi-switch 
理  mdi-sword 
ﲅ  mdi-sword_cross 
痢  mdi-sync 
罹  mdi-sync_alert 
裏  mdi-sync_off 
裡  mdi-tab 
ﱚ  mdi-tab_plus 
里  mdi-tab_unselected 
離  mdi-table 
ﴳ  mdi-table_column 
匿  mdi-table_column_plus_after 
溺  mdi-table_column_plus_before 
吝  mdi-table_column_remove 
燐  mdi-table_column_width 
璘  mdi-table_edit 
藺  mdi-table_large 
ﴴ  mdi-table_of_contents 
ﴵ  mdi-table_row 
隣  mdi-table_row_height 
鱗  mdi-table_row_plus_after 
麟  mdi-table_row_plus_before 
林  mdi-table_row_remove 
ﴶ  mdi-table_settings 
淋  mdi-tablet 
臨  mdi-tablet_android 
立  mdi-tablet_ipad 
ﱠ  mdi-taco 
笠  mdi-tag 
粒  mdi-tag_faces 
ﮉ  mdi-tag_heart 
狀  mdi-tag_multiple 
炙  mdi-tag_outline 
ﰠ  mdi-tag_plus 
ﰡ  mdi-tag_remove 
識  mdi-tag_text_outline 
什  mdi-target 
茶  mdi-taxi 
刺  mdi-teamviewer 
切  mdi-telegram 
度  mdi-television 
ﴷ  mdi-television_box 
ﳲ  mdi-television_classic 
ﴸ  mdi-television_classic_off 
拓  mdi-television_guide 
ﴹ  mdi-television_off 
糖  mdi-temperature_celsius 
宅  mdi-temperature_fahrenheit 
洞  mdi-temperature_kelvin 
暴  mdi-tennis 
輻  mdi-tent 
行  mdi-terrain 
ﭧ  mdi-test_tube 
ﭨ  mdi-text_shadow 
降  mdi-text_to_speech 
見  mdi-text_to_speech_off 
﬍  mdi-textbox 
ﳳ  mdi-textbox_password 
廓  mdi-texture 
兀  mdi-theater 
嗀  mdi-theme_light_dark 
﨎  mdi-thermometer 
﨏  mdi-thermometer_lines 
ﳴ  mdi-thought_bubble 
ﳵ  mdi-thought_bubble_outline 
塚  mdi-thumb_down 
﨑  mdi-thumb_down_outline 
晴  mdi-thumb_up 
﨓  mdi-thumb_up_outline 
﨔  mdi-thumbs_up_down 
凞  mdi-ticket 
猪  mdi-ticket_account 
益  mdi-ticket_confirmation 
ﰢ  mdi-ticket_percent 
礼  mdi-tie 
ﰣ  mdi-tilde 
神  mdi-timelapse 
祥  mdi-timer 
福  mdi-timer_10 
靖  mdi-timer_3 
精  mdi-timer_off 
羽  mdi-timer_sand 
ﮫ  mdi-timer_sand_empty 
ﲊ  mdi-timer_sand_full 
﨟  mdi-timetable 
蘒  mdi-toggle_switch 
﨡  mdi-toggle_switch_off 
諸  mdi-tooltip 
﨣  mdi-tooltip_edit 
﨤  mdi-tooltip_image 
逸  mdi-tooltip_outline 
都  mdi-tooltip_outline_plus 
﨧  mdi-tooltip_text 
﨨  mdi-tooth 
﨩  mdi-tor 
ﭿ  mdi-tower_beach 
ﮀ  mdi-tower_fire 
ﴺ  mdi-towing 
ﳶ  mdi-trackpad 
飯  mdi-traffic_light 
飼  mdi-train 
館  mdi-tram 
鶴  mdi-transcribe 
郞  mdi-transcribe_close 
隷  mdi-transfer 
ﮬ  mdi-transit_transfer 
韛  mdi-translate 
ﰤ  mdi-treasure_chest 
侮  mdi-tree 
僧  mdi-trello 
免  mdi-trending_down 
勉  mdi-trending_neutral 
勤  mdi-trending_up 
卑  mdi-triangle 
喝  mdi-triangle_outline 
嘆  mdi-trophy 
器  mdi-trophy_award 
塀  mdi-trophy_outline 
墨  mdi-trophy_variant 
層  mdi-trophy_variant_outline 
屮  mdi-truck 
悔  mdi-truck_delivery 
ﲆ  mdi-truck_fast 
ﰥ  mdi-truck_trailer 
慨  mdi-tshirt_crew 
憎  mdi-tshirt_v 
懲  mdi-tumblr 
敏  mdi-tumblr_reblog 
שּׂ  mdi-tune 
ﭩ  mdi-tune_vertical 
既  mdi-twitch 
暑  mdi-twitter 
梅  mdi-twitter_box 
海  mdi-twitter_circle 
渚  mdi-twitter_retweet 
ﱇ  mdi-uber 
漢  mdi-ubuntu 
ﳷ  mdi-ultra_high_definition 
煮  mdi-umbraco 
爫  mdi-umbrella 
琢  mdi-umbrella_outline 
碑  mdi-undo 
社  mdi-undo_variant 
祉  mdi-unfold_less_horizontal 
ﱞ  mdi-unfold_less_vertical 
祈  mdi-unfold_more_horizontal 
ﱟ  mdi-unfold_more_vertical 
祐  mdi-ungroup 
ﮭ  mdi-unity 
祖  mdi-untappd 
ﮮ  mdi-update 
祝  mdi-upload 
ﴻ  mdi-upload_multiple 
ﯴ  mdi-upload_network 
禍  mdi-usb 
ﳸ  mdi-van_passenger 
ﳹ  mdi-van_utility 
ﳺ  mdi-vanish 
禎  mdi-vector_arrange_above 
穀  mdi-vector_arrange_below 
突  mdi-vector_circle 
節  mdi-vector_circle_variant 
練  mdi-vector_combine 
縉  mdi-vector_curve 
繁  mdi-vector_difference 
署  mdi-vector_difference_ab 
者  mdi-vector_difference_ba 
臭  mdi-vector_intersection 
艹  mdi-vector_line 
艹  mdi-vector_point 
著  mdi-vector_polygon 
褐  mdi-vector_polyline 
ﱈ  mdi-vector_radius 
鉶  mdi-vector_rectangle 
視  mdi-vector_selection 
  mdi-vector_square 
謁  mdi-vector_triangle 
謹  mdi-vector_union 
勺  mdi-venmo 
賓  mdi-verified 
贈  mdi-vibrate 
辶  mdi-video 
ﳻ  mdi-video_3d 
ﴼ  mdi-video_4k_box 
ﴽ  mdi-video_input_antenna 
﴾  mdi-video_input_component 
﴿  mdi-video_input_hdmi 
﵀  mdi-video_input_svideo 
逸  mdi-video_off 
難  mdi-video_switch 
響  mdi-view_agenda 
頻  mdi-view_array 
恵  mdi-view_carousel 
𤋮  mdi-view_column 
舘  mdi-view_dashboard 
﵁  mdi-view_dashboard_variant 
﩮  mdi-view_day 
﩯  mdi-view_grid 
並  mdi-view_headline 
况  mdi-view_list 
全  mdi-view_module 
ﰦ  mdi-view_parallel 
侀  mdi-view_quilt 
ﰧ  mdi-view_sequential 
充  mdi-view_stream 
冀  mdi-view_week 
勇  mdi-vimeo 
﬎  mdi-violin 
﬏  mdi-visualstudio 
喝  mdi-vk 
啕  mdi-vk_box 
喙  mdi-vk_circle 
嗢  mdi-vlc 
響  mdi-voice 
塚  mdi-voicemail 
墳  mdi-volume_high 
奄  mdi-volume_low 
奔  mdi-volume_medium 
ﱜ  mdi-volume_minus 
ﱝ  mdi-volume_mute 
婢  mdi-volume_off 
ﱛ  mdi-volume_plus 
嬨  mdi-vpn 
﵂  mdi-vuejs 
廒  mdi-walk 
ﳼ  mdi-wall 
廙  mdi-wallet 
彩  mdi-wallet_giftcard 
徭  mdi-wallet_membership 
惘  mdi-wallet_travel 
慎  mdi-wan 
ﰨ  mdi-washing_machine 
愈  mdi-watch 
憎  mdi-watch_export 
慠  mdi-watch_import 
ﮯ  mdi-watch_vibrate 
懲  mdi-water 
戴  mdi-water_off 
揄  mdi-water_percent 
搜  mdi-water_pump 
﬑  mdi-watermark 
ﲋ  mdi-waves 
摒  mdi-weather_cloudy 
敖  mdi-weather_fog 
晴  mdi-weather_hail 
朗  mdi-weather_lightning 
ﭼ  mdi-weather_lightning_rainy 
望  mdi-weather_night 
杖  mdi-weather_partlycloudy 
歹  mdi-weather_pouring 
殺  mdi-weather_rainy 
流  mdi-weather_snowy 
ﭽ  mdi-weather_snowy_rainy 
滛  mdi-weather_sunny 
滋  mdi-weather_sunset 
漢  mdi-weather_sunset_down 
瀞  mdi-weather_sunset_up 
煮  mdi-weather_windy 
瞧  mdi-weather_windy_variant 
爵  mdi-web 
犯  mdi-webcam 
אַ  mdi-webhook 
ﰩ  mdi-webpack 
﬐  mdi-wechat 
猪  mdi-weight 
瑱  mdi-weight_kilogram 
甆  mdi-whatsapp 
画  mdi-wheelchair_accessibility 
瘝  mdi-white_balance_auto 
瘟  mdi-white_balance_incandescent 
益  mdi-white_balance_iridescent 
盛  mdi-white_balance_sunny 
ﰪ  mdi-widgets 
直  mdi-wifi 
睊  mdi-wifi_off 
着  mdi-wii 
ﰫ  mdi-wiiu 
磌  mdi-wikipedia 
窱  mdi-window_close 
節  mdi-window_closed 
类  mdi-window_maximize 
絛  mdi-window_minimize 
練  mdi-window_open 
缾  mdi-window_restore 
者  mdi-windows 
荒  mdi-wordpress 
華  mdi-worker 
蝹  mdi-wrap 
襁  mdi-wrench 
覆  mdi-wunderlist 
﵃  mdi-xamarin 
﵄  mdi-xamarin_outline 
ﭲ  mdi-xaml 
視  mdi-xbox 
調  mdi-xbox_controller 
ﱉ  mdi-xbox_controller_battery_alert 
ﱊ  mdi-xbox_controller_battery_empty 
ﱋ  mdi-xbox_controller_battery_full 
ﱌ  mdi-xbox_controller_battery_low 
ﱍ  mdi-xbox_controller_battery_medium 
ﱎ  mdi-xbox_controller_battery_unknown 
諸  mdi-xbox_controller_off 
請  mdi-xda 
謁  mdi-xing 
諾  mdi-xing_box 
諭  mdi-xing_circle 
謹  mdi-xml 
ﳽ  mdi-xmpp 
ﲇ  mdi-yammer 
變  mdi-yeast 
贈  mdi-yelp 
ﭾ  mdi-yin_yang 
﵅  mdi-youtube_creator_studio 
﵆  mdi-youtube_gaming 
輸  mdi-youtube_play 
磊  mdi-youtube_tv 
遲  mdi-zip_box 
  oct-alert 
  oct-arrow_down 
  oct-arrow_left 
  oct-arrow_right 
  oct-arrow_small_down 
  oct-arrow_small_left 
  oct-arrow_small_right 
  oct-arrow_small_up 
  oct-arrow_up 
  oct-beaker 
  oct-bell 
  oct-bold 
  oct-book 
  oct-bookmark 
  oct-briefcase 
  oct-broadcast 
  oct-browser 
  oct-bug 
  oct-calendar 
  oct-check 
  oct-checklist 
  oct-chevron_down 
  oct-chevron_left 
  oct-chevron_right 
  oct-chevron_up 
  oct-circle_slash 
  oct-circuit_board 
  oct-clippy 
  oct-clock 
  oct-cloud_download 
  oct-cloud_upload 
  oct-code 
  oct-comment 
  oct-comment_discussion 
  oct-credit_card 
  oct-dash 
  oct-dashboard 
  oct-database 
  oct-desktop_download 
  oct-device_camera 
  oct-device_camera_video 
  oct-device_desktop 
  oct-device_mobile 
  oct-diff 
  oct-diff_added 
  oct-diff_ignored 
  oct-diff_modified 
  oct-diff_removed 
  oct-diff_renamed 
  oct-ellipses 
  oct-ellipsis 
  oct-eye 
  oct-file 
  oct-file_binary 
  oct-file_code 
  oct-file_directory 
  oct-file_media 
  oct-file_pdf 
  oct-file_submodule 
  oct-file_symlink_directory 
  oct-file_symlink_file 
  oct-file_text 
  oct-file_zip 
  oct-flame 
  oct-fold 
  oct-gear 
  oct-gift 
  oct-gist 
  oct-gist_secret 
  oct-git_branch 
  oct-git_commit 
  oct-git_compare 
  oct-git_merge 
  oct-git_pull_request 
  oct-globe 
  oct-grabber 
  oct-graph 
♥  oct-heart 
  oct-history 
  oct-home 
  oct-horizontal_rule 
  oct-hubot 
  oct-inbox 
  oct-info 
  oct-issue_closed 
  oct-issue_opened 
  oct-issue_reopened 
  oct-italic 
  oct-jersey 
  oct-key 
  oct-keyboard 
  oct-law 
  oct-light_bulb 
  oct-link 
  oct-link_external 
  oct-list_ordered 
  oct-list_unordered 
  oct-location 
  oct-lock 
  oct-logo_gist 
  oct-logo_github 
  oct-mail 
  oct-mail_read 
  oct-mail_reply 
  oct-mark_github 
  oct-markdown 
  oct-megaphone 
  oct-mention 
  oct-milestone 
  oct-mirror 
  oct-mortar_board 
  oct-mute 
  oct-no_newline 
  oct-octoface 
  oct-organization 
  oct-package 
  oct-paintcan 
  oct-pencil 
  oct-person 
  oct-pin 
  oct-plug 
  oct-plus 
  oct-plus_small 
  oct-primitive_dot 
  oct-primitive_square 
  oct-pulse 
  oct-question 
  oct-quote 
  oct-radio_tower 
  oct-reply 
  oct-repo 
  oct-repo_clone 
  oct-repo_force_push 
  oct-repo_forked 
  oct-repo_pull 
  oct-repo_push 
  oct-rocket 
  oct-rss 
  oct-ruby 
  oct-search 
  oct-server 
  oct-settings 
  oct-shield 
  oct-sign_in 
  oct-sign_out 
  oct-smiley 
  oct-squirrel 
  oct-star 
  oct-stop 
  oct-sync 
  oct-tag 
  oct-tasklist 
  oct-telescope 
  oct-terminal 
  oct-text_size 
  oct-three_bars 
  oct-thumbsdown 
  oct-thumbsup 
  oct-tools 
  oct-trashcan 
  oct-triangle_down 
  oct-triangle_left 
  oct-triangle_right 
  oct-triangle_up 
  oct-unfold 
  oct-unmute 
  oct-unverified 
  oct-verified 
  oct-versions 
  oct-watch 
  oct-x 
⚡  oct-zap 
  pl-branch 
  pl-current_line 
  pl-hostname 
  pl-left_hard_divider 
  pl-left_soft_divider 
  pl-line_number 
  pl-readonly 
  pl-right_hard_divider 
  pl-right_soft_divider 
  ple-backslash_separator 
  ple-backslash_separator_redundant 
  ple-column_number 
  ple-current_column 
  ple-flame_thick 
  ple-flame_thick_mirrored 
  ple-flame_thin 
  ple-flame_thin_mirrored 
  ple-forwardslash_separator 
  ple-forwardslash_separator_redundant 
  ple-honeycomb 
  ple-honeycomb_outline 
  ple-ice_waveform 
  ple-ice_waveform_mirrored 
  ple-left_half_circle_thick 
  ple-left_half_circle_thin 
  ple-lego_block_facing 
  ple-lego_block_sideways 
  ple-lego_separator 
  ple-lego_separator_thin 
  ple-lower_left_triangle 
  ple-lower_right_triangle 
  ple-pixelated_squares_big 
  ple-pixelated_squares_big_mirrored 
  ple-pixelated_squares_small 
  ple-pixelated_squares_small_mirrored 
  ple-right_half_circle_thick 
  ple-right_half_circle_thin 
  ple-trapezoid_top_bottom 
  ple-trapezoid_top_bottom_mirrored 
  ple-upper_left_triangle 
  ple-upper_right_triangle 
  pom-away 
  pom-clean_code 
  pom-external_interruption 
  pom-internal_interruption 
  pom-long_pause 
  pom-pair_programming 
  pom-pomodoro_done 
  pom-pomodoro_estimated 
  pom-pomodoro_squashed 
  pom-pomodoro_ticking 
  pom-short_pause 
  seti-apple 
  seti-argdown 
  seti-asm 
  seti-audio 
  seti-babel 
  seti-bazel 
  seti-bicep 
  seti-bower 
  seti-bsl 
  seti-c 
  seti-c_sharp 
  seti-cake 
  seti-cake_php 
  seti-checkbox 
  seti-checkbox_unchecked 
  seti-cjsx 
  seti-clock 
  seti-clojure 
  seti-code_climate 
  seti-code_search 
  seti-coffee 
  seti-coldfusion 
  seti-config 
  seti-cpp 
  seti-crystal 
  seti-crystal_embedded 
  seti-css 
  seti-csv 
  seti-cu 
  seti-d 
  seti-dart 
  seti-db 
  seti-default 
  seti-deprecation_cop 
  seti-docker 
  seti-editorconfig 
  seti-ejs 
  seti-elixir 
  seti-elixir_script 
  seti-elm 
  seti-error 
  seti-eslint 
  seti-ethereum 
  seti-f_sharp 
  seti-favicon 
  seti-firebase 
  seti-firefox 
  seti-folder 
  seti-font 
  seti-git 
  seti-git_folder 
  seti-git_ignore 
  seti-github 
  seti-gitlab 
  seti-go 
  seti-go2 
  seti-godot 
  seti-gradle 
  seti-grails 
  seti-graphql 
  seti-grunt 
  seti-gulp 
  seti-hacklang 
  seti-haml 
  seti-happenings 
  seti-haskell 
  seti-haxe 
  seti-heroku 
  seti-hex 
  seti-home 
  seti-html 
  seti-ignored 
  seti-illustrator 
  seti-image 
  seti-info 
  seti-ionic 
  seti-jade 
  seti-java 
  seti-javascript 
  seti-jenkins 
  seti-jinja 
  seti-json 
  seti-julia 
  seti-karma 
  seti-kotlin 
  seti-less 
  seti-license 
  seti-liquid 
  seti-livescript 
  seti-lock 
  seti-lua 
  seti-makefile 
  seti-markdown 
  seti-maven 
  seti-mdo 
  seti-mustache 
  seti-new_file 
  seti-nim 
  seti-notebook 
  seti-npm 
  seti-npm_ignored 
  seti-nunjucks 
  seti-ocaml 
  seti-odata 
  seti-pddl 
  seti-pdf 
  seti-perl 
  seti-photoshop 
  seti-php 
  seti-pipeline 
  seti-plan 
  seti-platformio 
  seti-play_arrow 
  seti-powershell 
  seti-prisma 
  seti-project 
  seti-prolog 
  seti-pug 
  seti-puppet 
  seti-purescript 
  seti-python 
  seti-r 
  seti-rails 
  seti-react 
  seti-reasonml 
  seti-rescript 
  seti-rollup 
  seti-ruby 
  seti-rust 
  seti-salesforce 
  seti-sass 
  seti-sbt 
  seti-scala 
  seti-search 
  seti-settings 
  seti-shell 
  seti-slim 
  seti-smarty 
  seti-spring 
  seti-stylelint 
  seti-stylus 
  seti-sublime 
  seti-svelte 
  seti-svg 
  seti-swift 
  seti-terraform 
  seti-tex 
  seti-text 
  seti-time_cop 
  seti-todo 
  seti-tsconfig 
  seti-twig 
  seti-typescript 
  seti-vala 
  seti-video 
  seti-vue 
  seti-wasm 
  seti-wat 
  seti-webpack 
  seti-wgt 
  seti-word 
  seti-xls 
  seti-xml 
  seti-yarn 
  seti-yml 
  seti-zig 
  seti-zip 
  weather-alien 
  weather-aliens 
  weather-barometer 
  weather-celsius 
  weather-cloud 
  weather-cloud_down 
  weather-cloud_refresh 
  weather-cloud_up 
  weather-cloudy 
  weather-cloudy_gusts 
  weather-cloudy_windy 
  weather-day_cloudy 
  weather-day_cloudy_gusts 
  weather-day_cloudy_high 
  weather-day_cloudy_windy 
  weather-day_fog 
  weather-day_hail 
  weather-day_haze 
  weather-day_light_wind 
  weather-day_lightning 
  weather-day_rain 
  weather-day_rain_mix 
  weather-day_rain_wind 
  weather-day_showers 
  weather-day_sleet 
  weather-day_sleet_storm 
  weather-day_snow 
  weather-day_snow_thunderstorm 
  weather-day_snow_wind 
  weather-day_sprinkle 
  weather-day_storm_showers 
  weather-day_sunny 
  weather-day_sunny_overcast 
  weather-day_thunderstorm 
  weather-day_windy 
  weather-degrees 
  weather-direction_down 
  weather-direction_down_left 
  weather-direction_down_right 
  weather-direction_left 
  weather-direction_right 
  weather-direction_up 
  weather-direction_up_left 
  weather-direction_up_right 
  weather-dust 
  weather-earthquake 
  weather-fahrenheit 
  weather-fire 
  weather-flood 
  weather-fog 
  weather-gale_warning 
  weather-hail 
  weather-horizon 
  weather-horizon_alt 
  weather-hot 
  weather-humidity 
  weather-hurricane 
  weather-hurricane_warning 
  weather-lightning 
  weather-lunar_eclipse 
  weather-meteor 
  weather-moon_alt_first_quarter 
  weather-moon_alt_full 
  weather-moon_alt_new 
  weather-moon_alt_third_quarter 
  weather-moon_alt_waning_crescent_1 
  weather-moon_alt_waning_crescent_2 
  weather-moon_alt_waning_crescent_3 
  weather-moon_alt_waning_crescent_4 
  weather-moon_alt_waning_crescent_5 
  weather-moon_alt_waning_crescent_6 
  weather-moon_alt_waning_gibbous_1 
  weather-moon_alt_waning_gibbous_2 
  weather-moon_alt_waning_gibbous_3 
  weather-moon_alt_waning_gibbous_4 
  weather-moon_alt_waning_gibbous_5 
  weather-moon_alt_waning_gibbous_6 
  weather-moon_alt_waxing_crescent_1 
  weather-moon_alt_waxing_crescent_2 
  weather-moon_alt_waxing_crescent_3 
  weather-moon_alt_waxing_crescent_4 
  weather-moon_alt_waxing_crescent_5 
  weather-moon_alt_waxing_crescent_6 
  weather-moon_alt_waxing_gibbous_1 
  weather-moon_alt_waxing_gibbous_2 
  weather-moon_alt_waxing_gibbous_3 
  weather-moon_alt_waxing_gibbous_4 
  weather-moon_alt_waxing_gibbous_5 
  weather-moon_alt_waxing_gibbous_6 
  weather-moon_first_quarter 
  weather-moon_full 
  weather-moon_new 
  weather-moon_third_quarter 
  weather-moon_waning_crescent_1 
  weather-moon_waning_crescent_2 
  weather-moon_waning_crescent_3 
  weather-moon_waning_crescent_4 
  weather-moon_waning_crescent_5 
  weather-moon_waning_crescent_6 
  weather-moon_waning_gibbous_1 
  weather-moon_waning_gibbous_2 
  weather-moon_waning_gibbous_3 
  weather-moon_waning_gibbous_4 
  weather-moon_waning_gibbous_5 
  weather-moon_waning_gibbous_6 
  weather-moon_waxing_crescent_1 
  weather-moon_waxing_crescent_2 
  weather-moon_waxing_crescent_3 
  weather-moon_waxing_crescent_4 
  weather-moon_waxing_crescent_5 
  weather-moon_waxing_crescent_6 
  weather-moon_waxing_gibbous_1 
  weather-moon_waxing_gibbous_2 
  weather-moon_waxing_gibbous_3 
  weather-moon_waxing_gibbous_4 
  weather-moon_waxing_gibbous_5 
  weather-moon_waxing_gibbous_6 
  weather-moonrise 
  weather-moonset 
  weather-na 
  weather-night_alt_cloudy 
  weather-night_alt_cloudy_gusts 
  weather-night_alt_cloudy_high 
  weather-night_alt_cloudy_windy 
  weather-night_alt_hail 
  weather-night_alt_lightning 
  weather-night_alt_partly_cloudy 
  weather-night_alt_rain 
  weather-night_alt_rain_mix 
  weather-night_alt_rain_wind 
  weather-night_alt_sleet 
  weather-night_alt_sleet_storm 
  weather-night_alt_snow 
  weather-night_alt_snow_thunderstorm 
  weather-night_alt_snow_wind 
  weather-night_alt_sprinkle 
  weather-night_alt_storm_showers 
  weather-night_alt_thunderstorm 
  weather-night_clear 
  weather-night_cloudy 
  weather-night_cloudy_gusts 
  weather-night_cloudy_high 
  weather-night_cloudy_windy 
  weather-night_fog 
  weather-night_hail 
  weather-night_lightning 
  weather-night_partly_cloudy 
  weather-night_rain 
  weather-night_rain_mix 
  weather-night_rain_wind 
  weather-night_showers 
  weather-night_sleet 
  weather-night_sleet_storm 
  weather-night_snow 
  weather-night_snow_thunderstorm 
  weather-night_snow_wind 
  weather-night_sprinkle 
  weather-night_storm_showers 
  weather-night_thunderstorm 
  weather-rain 
  weather-rain_mix 
  weather-rain_wind 
  weather-raindrop 
  weather-raindrops 
  weather-refresh 
  weather-refresh_alt 
  weather-sandstorm 
  weather-showers 
  weather-sleet 
  weather-small_craft_advisory 
  weather-smog 
  weather-smoke 
  weather-snow 
  weather-snow_wind 
  weather-snowflake_cold 
  weather-solar_eclipse 
  weather-sprinkle 
  weather-stars 
  weather-storm_showers 
  weather-storm_warning 
  weather-strong_wind 
  weather-sunrise 
  weather-sunset 
  weather-thermometer 
  weather-thermometer_exterior 
  weather-thermometer_internal 
  weather-thunderstorm 
  weather-time_1 
  weather-time_10 
  weather-time_11 
  weather-time_12 
  weather-time_2 
  weather-time_3 
  weather-time_4 
  weather-time_5 
  weather-time_6 
  weather-time_7 
  weather-time_8 
  weather-time_9 
  weather-tornado 
  weather-train 
  weather-tsunami 
  weather-umbrella 
  weather-volcano 
  weather-wind_beaufort_0 
  weather-wind_beaufort_1 
  weather-wind_beaufort_10 
  weather-wind_beaufort_11 
  weather-wind_beaufort_12 
  weather-wind_beaufort_2 
  weather-wind_beaufort_3 
  weather-wind_beaufort_4 
  weather-wind_beaufort_5 
  weather-wind_beaufort_6 
  weather-wind_beaufort_7 
  weather-wind_beaufort_8 
  weather-wind_beaufort_9 
  weather-wind_direction 
  weather-wind_east 
  weather-wind_north 
  weather-wind_north_east 
  weather-wind_north_west 
  weather-wind_south 
  weather-wind_south_east 
  weather-wind_south_west 
  weather-wind_west 
  weather-windy 